---
# SystemD
galaxy_systemd_mode: ""
galaxy_systemd_celery: true
galaxy_systemd_celery_pool: threads
galaxy_systemd_celery_workers: 1
galaxy_systemd_celery_concurrency: 32
galaxy_systemd_celery_log_level: DEBUG
galaxy_systemd_celery_env: ""
galaxy_systemd_celery_beat_schedule_path: "/opt/galaxy/celery/celery-beat-schedule"
galaxy_systemd_memory_limit_celery: 20G