---
cvmfs_stratum1_create_directory: false

cvmfs_stratum1_cache_dir:
  dir: /var/cache/squid/
  # 'Mbytes' is the amount of disk space (MB) to use under this
  # directory.  The default is 100 MB.  Change this to suit your
  # configuration.  Do NOT put the size of your disk drive here.
  # Instead, if you want Squid to use the entire disk drive,
  # subtract 20% and use that value.
  size: "{{ 1024 * 1024 }}" # 1 TB

usegalaxy_eu_autofs_mounts:
 - data

certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_auto_renew_hour: 5
certbot_auto_renew_minute: 33

certbot_environment: production #staging
certbot_domains:
  - "{{ hostname }}"
certbot_agree_tos: --agree-tos
certbot_admin_email: security@usegalaxy.eu
certbot_post_renewal: |
    mkdir -p /etc/ssl/private/
    chmod 750 /etc/ssl/private/
    cp /etc/letsencrypt/live/{{ hostname }}/fullchain.pem /etc/ssl/certs/{{ hostname }}
    cp /etc/letsencrypt/live/{{ hostname }}/privkey.pem   /etc/ssl/private/privkey.pem
    chmod 644 /etc/ssl/certs/{{ hostname }}
    chmod 640 /etc/ssl/private/privkey.pem
    chown root:nginx /etc/ssl/private/privkey.pem
    chown root:nginx -R /etc/ssl/private/privkey.pem
    systemctl restart nginx || true
