---
ssh_allow_root_with_key: true

galaxy_root_dir: /usr/local/galaxy/galaxy-dist
galaxy_tool_dir: "{{ galaxy_root_dir }}/tools"
galaxy_conf_dir: "{{ galaxy_root_dir }}/config"
galaxy_user: galaxy
galaxy_group: galaxy

galaxy_test_user:
    handlers:
        - "handler0"
        - "handler1"
        - "handler2"
        - "handler3"
        - "handler4"
        - "handler5"
        - "handler6"
        - "handler7"
        - "handler8"
        - "handler9"
        - "handler10"
        - "handler11"
        - "drmaa"
        - "condor"
