# Certbot
certbot_auto_renew_hour: 3
certbot_auto_renew_minute: 30

certbot_auth_method: --webroot
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx

certbot_post_renewal: |
    systemctl restart nginx || true

# NGINX
nginx_enable_default_server: false
nginx_ssl_servers:
  - grafana-ssl
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

# Grafana
grafana_instance: "{{ hostname }}"
grafana_address: "127.0.0.1"
grafana_url: "https://stats.galaxyproject.eu"
grafana_server:
    domain: "{{ hostname }}"
    root_url: "https://%(domain)s/"

grafana_users:
    default_theme: "light"

grafana_security:
    admin_user: admin
    admin_password: "{{ grafana_auth_admin_password }}"
    allow_embedding: "true"
    cookie_secure: "true"

grafana_auth:
    anonymous:
        enabled: "true"
        org_name: "UseGalaxy.eu"
        org_role: "Viewer"

    github:
        enabled: "true"
        allow_sign_up: "true"
        client_id: "{{ grafana_auth__github_client_id }}"
        client_secret: "{{ grafana_auth__github_client_secret }}"
        scopes: "user:email,read:org"
        auth_url: "https://github.com/login/oauth/authorize"
        token_url: "https://github.com/login/oauth/access_token"
        api_url: "https://api.github.com/user"
        allowed_organisations: "usegalaxy.eu galaxyproject"

grafana_datasources:
 - name: Galaxy
   type: influxdb
   access: proxy
   url: "{{ influxdb.url }}"
   isDefault: true
   version: 1
   editable: false
   database: galaxy
   username: "{{ influxdb.grafana.username }}"
   password: "{{ influxdb.grafana.password }}"
 - name: Galaxy Historical
   type: influxdb
   access: proxy
   url: "{{ influxdb.url }}"
   version: 1
   editable: false
   database: galaxy_stats
   username: "{{ influxdb.grafana.username }}"
   password: "{{ influxdb.grafana.password }}"
 - name: GRT Tool Usage
   type: influxdb
   access: proxy
   url: "{{ influxdb.url }}"
   version: 1
   editable: false
   database: grt
   username: "{{ influxdb.grafana.username }}"
   password: "{{ influxdb.grafana.password }}"
 - name: InfluxDB - internal
   type: influxdb
   access: proxy
   url: "{{ influxdb.url }}"
   version: 1
   editable: false
   database: _internal
   username: "{{ influxdb.grafana.username }}"
   password: "{{ influxdb.grafana.password }}"
 - name: Notifications
   type: influxdb
   access: proxy
   url: "{{ influxdb.url }}"
   version: 1
   editable: false
   database: notifications
   username: "{{ influxdb.grafana.username }}"
   password: "{{ influxdb.grafana.password }}"


#telegraf_plugins_extra:
  #simple_nagios:
    #plugin: "exec"
    #config:
      #- commands = ["/usr/bin/simple-nagios"]
      #- timeout = "120s"
      #- data_format = "influx"
      #- interval = "1m"

  #galaxy_jobs:
    #plugin: "exec"
    #config:
      #- commands = ["/usr/local/bin/simple-galaxy"]
      #- timeout = "180s"
      #- data_format = "influx"
      #- interval = "15m"

  #count_tools:
    #plugin: "exec"
    #config:
      #- commands = ["/opt/pgs/count-tools.sh"]
      #- timeout = "10m"
      #- data_format = "influx"
      #- interval = "24h"

  #ssl_expiry:
    #plugin: "exec"
    #config:
      #- |
        #commands = [
          ## A couple of usegalaxy.eu subdomains.
          #"/usr/bin/simple-ssl-check usegalaxy.eu",
          #"/usr/bin/simple-ssl-check metagenomics.usegalaxy.eu",
          ## Proxy + Proxied services
          #"/usr/bin/simple-ssl-check proxy.galaxyproject.eu",
          #"/usr/bin/simple-ssl-check build.galaxyproject.eu",
          #"/usr/bin/simple-ssl-check influxdb.galaxyproject.eu 8086",
          #"/usr/bin/simple-ssl-check influxdb.galaxyproject.eu",
          #"/usr/bin/simple-ssl-check stats.galaxyproject.eu",
          #"/usr/bin/simple-ssl-check telescope.galaxyproject.eu",
          ## RZ
          #"/usr/bin/simple-ssl-check cloud.denbi.uni-freiburg.de",
          #"/usr/bin/simple-ssl-check mon01.bwcloud.uni-freiburg.de",
        #]
      #- timeout = "15s"
      #- data_format = "influx"
      #- interval = "15m"

  #dns_query:
    #config:
      ##            cf         goog       quad9      opendns           BelWü
      #- servers = ["1.1.1.1", "8.8.8.8", "9.9.9.9", "208.67.222.222", "132.230.201.111", "132.230.200.200"]
      #- timeout = 15
      #- domains = ["google.com", "usegalaxy.eu", "registry.npmjs.org"]
      #- record_type = "A"
      #- interval = "5m"

#galaxy_test_url: https://usegalaxy.eu
#galaxy_test_user:
    #api_key: "{{ galaxy_test_user__api_key }}"
    #username: bot@usegalaxy.eu
    #password: "{{ galaxy_test_user__password }}"
    #handlers:
        #- "handler0"
        #- "handler1"
        #- "handler2"
        #- "handler3"
        #- "handler4"
        #- "handler5"
        #- "handler6"
        #- "handler7"
        #- "handler8"
        #- "handler9"
        #- "handler10"
        #- "handler11"
        #- "drmaa"
        #- "condor"

#galaxy_nagios_urls:
  #ftp_tests:
    #- name: ftp_ssl
      #url: ftp://ftp.usegalaxy.eu

  #ftp_age_tests:
    #- name: ftp_age
      #url: https://usegalaxy.eu

  #http_tests:
    #- name: home_nossl
      #url: "http://usegalaxy.eu"
      #code: 301
    #- name: home
      #url: "https://usegalaxy.eu"
      #code: 200
    #- name: hicexplorer
      #url: "https://hicexplorer.usegalaxy.eu"
      #code: 200
    #- name: stats
      #url: "https://stats.galaxyproject.eu"
      #code: 200
    #- name: apollo
      #url: "https://apollo.usegalaxy.eu/apollo_api/annotator/index"
      #code: 200
    #- name: grt
      #url: "https://telescope.galaxyproject.eu/"
      #code: 200
    #- name: build
      #url: "https://build.galaxyproject.eu"
      #code: 200
    #- name: ftp_docs
      #url: "https://ftp.usegalaxy.eu"
      #code: 200
    #- name: influx
      #url: "{{ influxdb.url }}/ping"
      #code: 204
    #- name: phinch
      #url: "https://usegalaxy.eu/phinch/index.html"
      #code: 200
