aws_cli_credentials:
  - account: certbot@proxy
    homedir: /root
    owner: root
    group: root

haproxy_chroot: ''
haproxy_frontends:
    - name: https-in
      bind:
        - '*:80'
        - '*:443  ssl crt /etc/pki/tls/private/full.pem'
      mode: http
      custom_config:
        - 'acl certbot_path      path_beg /.well-known/'
        # Add header if this was over HTTPS
        - 'reqadd X-Forwarded-Proto:\ https if { ssl_fc }'
        # Unless this is going to certbot, redirect to HTTPS
        - 'redirect scheme https code 301 if !{ ssl_fc } !certbot_path'
        # ACLs
        - 'acl website_domain    hdr_dom(host) -i galaxyproject.eu'
        - 'acl main_domain       hdr_dom(host) -i usegalaxy.eu'
        - 'acl beta_domain       hdr_dom(host) -i beta.usegalaxy.eu'
        - 'acl apollo_path       path_beg /apollo/'
        - 'acl rabbit_path       path_beg /rabbit/'
        - 'acl welcome           path_beg /static/welcome.html'
        - 'acl basecss           path_beg /static/style/base.css'
        # Proxy our website
        - 'use_backend website   if website_domain'
        # Redirect some old stuff
        - 'redirect prefix https://stats.galaxyproject.eu  code 301 if { hdr(host) -i stats.usegalaxy.eu  }'
        - 'redirect prefix https://build.galaxyproject.eu  code 301 if { hdr(host) -i build.usegalaxy.eu  }'
        - 'redirect prefix https://sentry.galaxyproject.eu code 301 if { hdr(host) -i sentry.usegalaxy.eu  }'
        # Beta/test galaxy.
        - 'use_backend beta_special   if beta_domain welcome'
        - 'use_backend beta_special   if beta_domain basecss'
        - 'use_backend beta_base      if beta_domain'

      galaxy_hosts:
        - domain: usegalaxy.de
          id: de
        - domain: hicexplorer.usegalaxy.eu
          id: hic
        - domain: metagenomics.usegalaxy.eu
          id: metagenomics
        - domain: rna.usegalaxy.eu
          id: rna
        - domain: graphclust.usegalaxy.eu
          id: graphclust
        - domain: ecology.usegalaxy.eu
          id: ecology
        - domain: proteomics.usegalaxy.eu
          id: proteomics
        - domain: clipseq.usegalaxy.eu
          id: clipseq
        - domain: test.usegalaxy.eu
          id: test
          disable_default_backend: true
        - domain: old.usegalaxy.eu
          id: old
          disable_default_backend: true
        - domain: streetscience.usegalaxy.eu
          id: streetscience

# Custom error pages. TODO: automate.
#- 'errorfile 400 /etc/haproxy/errors/400.html'
#- 'errorfile 403 /etc/haproxy/errors/403.html'
#- 'errorfile 408 /etc/haproxy/errors/408.html'
#- 'errorfile 500 /etc/haproxy/errors/500.html'
#- 'errorfile 502 /etc/haproxy/errors/502.html'
#- 'errorfile 503 /etc/haproxy/errors/503.html'
#- 'errorfile 504 /etc/haproxy/errors/504.html'

haproxy_galaxy_backend: 'server server1 132.230.68.5:443 maxconn 128 ssl verify none'
haproxy_backends:
    - name: galaxy
      balance: roundrobin
      mode: http
      custom_config:
          # Retry requests up to 8 times. The default is 3
          # https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#4.2-retries
          - "retries 8"
          - "{{ haproxy_galaxy_backend }}"
    - name: beta_base
      balance: roundrobin
      mode: http
      custom_config:
          - 'server server1 sn04.bi.uni-freiburg.de:443 maxconn 32 ssl verify none'
    - name: beta_special
      balance: roundrobin
      mode: http
      custom_config:
          - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-beta.css\1\ HTTP/1.1'
          - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-beta.html\ HTTP/1.1'
          - 'server server1 sn04.bi.uni-freiburg.de:443 maxconn 32 ssl verify none'
    #- name: apollo
      #balance: roundrobin
      #mode: http
      #custom_config:
        #- 'server server1 apollo.usegalaxy.eu:443 maxconn 32 ssl verify none'
    - name: website
      balance: roundrobin
      mode: http
      custom_config:
        - 'http-request set-header Host usegalaxy-eu.github.io'
        - 'server server1 usegalaxy-eu.github.io:443 maxconn 32 ssl verify none'
    - name: rabbit
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /rabbit/(.*)\ HTTP/1.1 GET\ /\1\ HTTP/1.1'
        - 'server server1 localhost:15672 maxconn 32'
    - name: certbot
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 127.0.0.1:8118 maxconn 32'

    - name: old_base
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 132.230.68.85:443  maxconn 32'

    - name: old_special
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 132.230.68.85:443  maxconn 32'

    - name: test_base
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 192.52.33.7:80  maxconn 32'

    - name: test_special
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 192.52.33.7:80  maxconn 32'
        #- 'server server1 192.52.33.67:80 maxconn 32'

haproxy_global_vars:
    - 'ssl-default-bind-options no-sslv3 no-tls-tickets force-tlsv12'
    - 'ssl-default-bind-ciphers AES128+EECDH:AES128+EDH'

haproxy_stats: true

rabbitmq_version: 3.6.15-1
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_cz
    password: "{{ rabbitmq_password_galaxy_cz }}"
    vhost: /pulsar/galaxy_cz
  - user: galaxy_test
    password: "{{ rabbitmq_password_galaxy_test }}"
    vhost: /pulsar/galaxy_test

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_cz
  - /pulsar/galaxy_test

rabbitmq_plugins:
  - rabbitmq_management


rabbitmq_config:
- rabbit:
  #- tcp_listeners:
    #- "'0.0.0.0'": 5671
  - ssl_listeners:
    - "'0.0.0.0'": 5671
  - ssl_options:
    - cacertfile: /etc/ssl/certs/fullchain.pem
    - certfile: /etc/ssl/certs/cert.pem
    - keyfile: /etc/ssl/private/privkey.pem
    - fail_if_no_peer_cert: 'false'

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
  - plugin: rabbitmq
    config:
      - url = "http://localhost:15672"
      - username = "telegraf"
      - password = "{{ rabbitmq_password_telegraf }}"
