---
haproxy_chroot: ''
haproxy_frontends:
    - name: https-in
      bind:
        - '*:80'
        - '*:443  ssl crt /etc/pki/tls/private/full.pem'
      mode: http
      custom_config:
        - 'acl certbot_path      path_beg /.well-known/'
        # Add header if this was over HTTPS
        - 'reqadd X-Forwarded-Proto:\ https if { ssl_fc }'
        # Unless this is going to certbot, redirect to HTTPS
        - 'redirect scheme https code 301 if !{ ssl_fc } !certbot_path'
        # ACLs
        - 'acl apollo_path       path_beg /apollo/'
        - 'acl rabbit_path       path_beg /rabbit/'
        - 'acl welcome           path_beg /static/welcome.html'
        - 'acl basecss           path_beg /static/style/base.css'
        # Proxy our website
        - 'use_backend telescope if telescope_domain' # needs to come before website domain

      galaxy_hosts: "{{ galaxy_custom_sites }}"

haproxy_galaxy_backend: 'server server1 132.230.68.5:443 maxconn 128 ssl verify none'
haproxy_backends:
    - name: telescope
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 telescope.internal.galaxyproject.eu:80 maxconn 32'
    - name: rabbit
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /rabbit/(.*)\ HTTP/1.1 GET\ /\1\ HTTP/1.1'
        - 'server server1 localhost:15672 maxconn 32'
    - name: certbot
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 127.0.0.1:8118 maxconn 32'

haproxy_global_vars:
    - 'ssl-default-bind-options no-sslv3 no-tls-tickets force-tlsv12'
    - 'ssl-default-bind-ciphers AES128+EECDH:AES128+EDH'

haproxy_stats: true

rabbitmq_version: 3.6.15-1
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_cz
    password: "{{ rabbitmq_password_galaxy_cz }}"
    vhost: /pulsar/galaxy_cz
  - user: galaxy_test
    password: "{{ rabbitmq_password_galaxy_test }}"
    vhost: /pulsar/galaxy_test
  - user: vgcn_test
    password: "{{ rabbitmq_password_galaxy_vgcn }}"
    vhost: /pulsar/galaxy_vgcn

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_cz
  - /pulsar/galaxy_test
  - /pulsar/galaxy_vgcn

rabbitmq_plugins:
  - rabbitmq_management


rabbitmq_config:
- rabbit:
  #- tcp_listeners:
    #- "'0.0.0.0'": 5671
  - ssl_listeners:
    - "'0.0.0.0'": 5671
  - ssl_options:
    - cacertfile: /etc/ssl/certs/fullchain.pem
    - certfile: /etc/ssl/certs/cert.pem
    - keyfile: /etc/ssl/private/privkey.pem
    - fail_if_no_peer_cert: 'false'

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
  - plugin: rabbitmq
    config:
      - url = "http://localhost:15672"
      - username = "telegraf"
      - password = "{{ rabbitmq_password_telegraf }}"
