haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

haproxy_backend_servers:
- name: app1
  address: 192.168.0.1:80
- name: app2
  address: 192.168.0.2:80


haproxy_global_vars:
    - 'ssl-default-bind-options no-sslv3 no-tls-tickets force-tlsv12'
    - 'ssl-default-bind-ciphers AES128+EECDH:AES128+EDH'
