haproxy_chroot: ''
haproxy_frontends:
    - name: https-in
      bind:
        - '*:80'
        - '*:443 ssl crt /etc/haproxy/certs/complete.pem'
      mode: http
      custom_config:
        - 'acl certbot_path      path_beg /.well-known/'
        # Add header if this was over HTTPS
        - 'reqadd X-Forwarded-Proto:\ https if { ssl_fc }'
        # Unless this is going to certbot, redirect to HTTPS
        - 'redirect scheme https code 301 if !{ ssl_fc } !certbot_path'
        # ACLs
        - 'acl de_host           hdr_dom(host) -i usegalaxy.de'
        - 'acl hic_host          hdr_dom(host) -i hicexplorer.usegalaxy.eu'
        - 'acl metagenomics_host hdr_dom(host) -i metagenomics.usegalaxy.eu'
        - 'acl rna_host          hdr_dom(host) -i rna.usegalaxy.eu'
        - 'acl ecology_host      hdr_dom(host) -i ecology.usegalaxy.eu'
        - 'acl proteomics_host      hdr_dom(host) -i proteomics.usegalaxy.eu'
        - 'acl welcome           path_beg /static/welcome.html'
        - 'acl basecss           path_beg /static/style/base.css'
        - 'acl apollo_path       path_beg /apollo/'
        - 'acl rabbit_path       path_beg /rabbit/'
        # Which go to specific backends.
        - 'use_backend certbot     if certbot_path'
        - 'use_backend apollo      if apollo_path'
        - 'use_backend rabbit      if rabbit_path'
        - 'use_backend hicspecial  if hic_host welcome'
        - 'use_backend hicspecial  if hic_host basecss'
        - 'use_backend metaspecial if metagenomics_host welcome'
        - 'use_backend metaspecial if metagenomics_host basecss'
        - 'use_backend despecial   if de_host welcome'
        - 'use_backend despecial   if de_host basecss'
        - 'use_backend rnaspecial if rna_host welcome'
        - 'use_backend rnaspecial if rna_host basecss'
        - 'use_backend ecologyspecial if ecology_host welcome'
        - 'use_backend ecologyspecial if ecology_host basecss'
        - 'use_backend proteomicsspecial if proteomics_host welcome'
        - 'use_backend proteomicsspecial if proteomics_host basecss'
        - 'use_backend galaxy'


        # Custom error pages. TODO: automate.
        - 'errorfile 400 /etc/haproxy/errors/400.html'
        - 'errorfile 403 /etc/haproxy/errors/403.html'
        - 'errorfile 408 /etc/haproxy/errors/408.html'
        - 'errorfile 500 /etc/haproxy/errors/500.html'
        - 'errorfile 502 /etc/haproxy/errors/502.html'
        - 'errorfile 503 /etc/haproxy/errors/503.html'
        - 'errorfile 504 /etc/haproxy/errors/504.html'

haproxy_backends:
    - name: galaxy
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: metaspecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-metagenomics.css\1\ HTTP/1.1'
        - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-metagenomics.html\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: rnaspecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-rna.css\1\ HTTP/1.1'
        - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-rna.html\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: hicspecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-hic.css\1\ HTTP/1.1'
        - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-hic.html\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: ecologyspecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-ecology.css\1\ HTTP/1.1'
        - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-ecology.html\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: proteomicsspecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-proteomics.css\1\ HTTP/1.1'
        - 'reqrep ^GET\ /static/welcome.html\ HTTP/1.1 GET\ /static/welcome-proteomics.html\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: despecial
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /static/style/base.css(.*)\ HTTP/1.1 GET\ /static/style/base-de.css\1\ HTTP/1.1'
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: apollo
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 apollo.usegalaxy.eu:443 maxconn 32 ssl verify none'
    - name: rabbit
      balance: roundrobin
      mode: http
      custom_config:
        - 'reqrep ^GET\ /rabbit/(.*)\ HTTP/1.1 GET\ /\1\ HTTP/1.1'
        - 'server server1 localhost:15672 maxconn 32'
    - name: certbot
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 127.0.0.1:8118 maxconn 32'

haproxy_global_vars:
    - 'ssl-default-bind-options no-sslv3 no-tls-tickets force-tlsv12'
    - 'ssl-default-bind-ciphers AES128+EECDH:AES128+EDH'

haproxy_stats: true

rabbitmq_version: 3.6.15-1
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy_cz
    password: "{{ rabbitmq_password_galaxy_cz }}"
    vhost: /pulsar/galaxy_cz
  - user: galaxy_test
    password: "{{ rabbitmq_password_galaxy_test }}"
    vhost: /pulsar/galaxy_test

rabbitmq_vhosts:
  - /pulsar/galaxy_cz
  - /pulsar/galaxy_test

rabbitmq_plugins:
  - rabbitmq_management


rabbitmq_config:
- rabbit:
  #- tcp_listeners:
    #- "'0.0.0.0'": 5671
  - ssl_listeners:
    - 5671
  - ssl_options:
    - cacertfile: /etc/rabbitmq/tls/fullchain.pem
    - certfile: /etc/rabbitmq/tls/cert.pem
    - keyfile: /etc/rabbitmq/tls/privkey.pem
    - fail_if_no_peer_cert: 'false'

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
  - plugin: rabbitmq
    config:
      - url = "http://localhost:15672"
      - username = "telegraf"
      - password = "{{ rabbitmq_password_telegraf }}"
