haproxy_frontends:
    - name: http-in
      bind: '*:80'
      mode: http
      custom_config:
        - option httplog
        - option forwardfor
        - option http-server-close
        - option httpclose
        - acl app_letsencrypt path_beg /.well-known/acme-challenge/
        - use_backend certbot if app_letsencrypt
        - 'redirect scheme https code 301 if !{ ssl_fc }'
    - name: https-in
      bind: '*:443 ssl crt /etc/haproxy/certs/complete.pem'
      mode: http
      custom_config:
        - 'reqadd X-Forwarded-Proto:\ https'
        - 'default_backend galaxy'

haproxy_backends:
    - name: galaxy
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 132.230.68.85:443 maxconn 32 ssl verify none'
    - name: certbot
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 127.0.0.1:63443 maxconn 32'

haproxy_global_vars:
    - 'ssl-default-bind-options no-sslv3 no-tls-tickets force-tlsv12'
    - 'ssl-default-bind-ciphers AES128+EECDH:AES128+EDH'

haproxy_stats: true

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
