haproxy_chroot: ''
haproxy_frontends:
    - name: https-in
      bind:
        - '*:80'
      mode: http
      custom_config:
        - 'acl certbot_path      path_beg /.well-known/'
        # Add header if this was over HTTPS
        - 'reqadd X-Forwarded-Proto:\ https if { ssl_fc }'
        # ACLs
        - 'acl cvmfs_domain      hdr_dom(host) -i cvmfs1-ufr0.galaxyproject.eu'
        - 'acl galaxy_domain     hdr_dom(host) -i test.usegalaxy.eu'
        - 'use_backend cvmfs     if cvmfs_domain'
        # Beta/test galaxy.
        - 'use_backend galaxy'
      galaxy_hosts: []


haproxy_backends:
    - name: cvmfs
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 cvmfs1-ufr0.internal.galaxyproject.eu:80 maxconn 32'
    - name: galaxy
      balance: roundrobin
      mode: http
      custom_config:
          # Retry requests up to 8 times. The default is 3
          # https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#4.2-retries
          - "retries 8"
          - "server server1 test.internal.usegalaxy.eu:443 maxconn 128 ssl verify none"

haproxy_stats: true

telegraf_plugins_extra:
  haproxy:
    plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
