---
haproxy_chroot: ''
haproxy_frontends:
    - name: https-in
      bind:
        - '*:80'
      mode: http
      custom_config:
        - 'use_backend cvmfs'


haproxy_backends:
    - name: cvmfs
      balance: roundrobin
      mode: http
      custom_config:
        - 'server server1 cvmfs1-ufr0.internal.galaxyproject.eu:80 maxconn 32'

haproxy_stats: true

telegraf_plugins_extra:
  haproxy:
    plugin: haproxy
    config:
      - servers = ["http://127.0.0.1:8080/haproxy?stats"]
  rabbitmq:
    plugin: rabbitmq
    config:
      - url = "http://localhost:15672"
      - username = "telegraf"
      - password = "{{ rabbitmq_password_telegraf }}"

rabbitmq_version: 3.6.15-1
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_cz
    password: "{{ rabbitmq_password_galaxy_cz }}"
    vhost: /pulsar/galaxy_cz
  - user: galaxy_test
    password: "{{ rabbitmq_password_galaxy_test }}"
    vhost: /pulsar/galaxy_test
  - user: vgcn_test
    password: "{{ rabbitmq_password_galaxy_vgcn }}"
    vhost: /pulsar/galaxy_vgcn

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_cz
  - /pulsar/galaxy_test
  - /pulsar/galaxy_vgcn

rabbitmq_plugins:
  - rabbitmq_management


rabbitmq_config:
- rabbit:
  #- tcp_listeners:
    #- "'0.0.0.0'": 5671
  - ssl_listeners:
    - "'0.0.0.0'": 5671
  - ssl_options:
    - cacertfile: /etc/ssl/certs/fullchain.pem
    - certfile: /etc/ssl/certs/cert.pem
    - keyfile: /etc/ssl/private/privkey.pem
    - fail_if_no_peer_cert: 'false'

