---
# Autofs
autofs_service.install: true
autofs_service.enable: true

autofs_mount_points:
  - data

autofs_conf_files:
  data:
    - 0       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 1       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 2       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 3       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 4       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 5       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 6       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 7       -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - dnb01   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb02   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb03   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb04   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb05   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/&
    - dnb06   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb06
    - dnb07   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb07
    - dnb08   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/dnb08
    - db      -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - gxtst   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/ws01/galaxy-sync/test
    - gxkey   -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/ws01/galaxy-sync/main
    - jwd     -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/ws01/&
    - jwd01   -rw,hard,nosuid      zfs1.galaxyproject.eu:/export/&

# packages
software_groups_to_install:
  - admin
  - debug
  - editors
  - services
  - utils

# HTCondor
condor_host: "condor-cm.galaxyproject.eu"
condor_allow_write: "10.5.68.0/24, 132.230.223.0/24, 132.230.153.0/28"
condor_daemons:
  - COLLECTOR
  - MASTER
  - NEGOTIATOR
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
condor_network_interface: ens802f0.2368
condor_extra: |
  MASTER_UPDATE_INTERVAL = 150
  CLASSAD_LIFETIME = 300
  NEGOTIATOR_INTERVAL = 15
  NEGOTIATOR_UPDATE_INTERVAL = 100
  JOB_START_COUNT = 250
  JOB_START_DELAY = 0
  NEGOTIATOR_POST_JOB_RANK = isUndefined(RemoteOwner) * (10000 - TotalLoadAvg)

# PostgreSQL
postgresql_conf:
  - listen_addresses: "'*'"
  - max_connections: 512
  - shared_buffers: "4GB"
  - temp_buffers: "64MB"
  - max_prepared_transactions: 100
  - work_mem: "64MB"
  - maintenance_work_mem: "64MB"
# the following line throws an error in v13
#  - shared_preload_libraries: "'pg_stat_statements'"
  - checkpoint_completion_target: 0.9
  - random_page_cost: 1.0
  - effective_cache_size: "16GB"
#  - log_line_prefix: "'%t:%r:%u@%d:[%p]<%m>: '"
  - log_checkpoints: "on"
  - log_min_duration_statement: 100
postgresql_pg_hba_conf:
  - "host    postgres        galaxy          132.230.223.239/32      md5"
  - "host    postgres        galaxy-test     10.5.68.154/32          md5"
  - "host    galaxy          galaxy          132.230.223.239/32      md5"
  - "host    galaxy          galaxy-readonly 132.230.223.239/32      md5"
  - "host    tiaas           tiaas           132.230.223.239/32      md5"
  - "host    galaxy-test     galaxy-test     132.230.223.239/32      md5"
  - "host    galaxy-test     galaxy-test     10.5.68.0/24            md5"
  - "host    galaxy          galaxyftp       132.230.223.213/32      md5"
  - "host    galaxy          galaxyftp       10.5.68.0/24            md5"
  - "host    galaxy          galaxy-apollo   10.5.68.0/24            md5"
  - "host    apollo          apollo          10.5.68.0/24            md5"
  - "host    chado           apollo          10.5.68.0/24            md5"
  - "host    grt             grt             10.5.68.0/24            md5"
postgresql_pgdump_dir: "/var/lib/pgsql/pgdump"
