---
toolbox:
    toolbox_sections:
      - name: Genomics (NGS)
        include_sections:
        - Variant calling
        - Epigenetics
        - Assembly
        - RAD-seq
        - Genome editing

      - name: Metagenomics
        include_sections:
        - Metagenomic analyses
        - Qiime
        - Mothur

      - name: Proteomics
        include_sections:
        - Proteomics

      - name: Metabolomics
        include_sections:
        - Metabolomics

      - name: Cheminformatics
        include_sections:
        - ChemicalToolBox

      - name: Genome Annotation
        include_sections:
        - Annotation
        - OBO Ontology manipulatoin
