---
# create_user task
handy_groups:
  - group_name: galaxy
    group_gid: 999

handy_users:
  - user_name: galaxy
    user_uid: 999
    user_comment: rustus Service-Acct
    user_group: galaxy

# Autofs
autofs_service:
  install: true
  enable: true
nfs_kernel_tuning: true

autofs_mount_points:
  - data
  - gxtest
  - gxkey
  - jwd

# usegalaxy_eu.handy.os_setup
## packages
software_groups_to_install:
  - editors
  - utils

## kernel_5
kernel_5_package: kernel-ml
