---

- name: Install packages for Kerberos client (Heimdal)
  apt:
    pkg: "{{ item }}"
  with_items:
    - heimdal-clients
    - krb5-config
    - libsasl2-modules-gssapi-heimdal
  when: kerberos_implementation == "heimdal"

- name: Install packages for Kerberos client (MIT)
  apt:
    pkg: "{{ item }}"
  with_items:
    - krb5-user
    - krb5-config
    - libsasl2-modules-gssapi-mit
  when: kerberos_implementation == "mit"

- name: Install krb5.conf
  template:
    src: "krb5.conf.j2"
    dest: "{{ kerberos_krb5_conf_dest }}"
    mode: 0444
    backup: yes

- include: k5login.yml
  when: k5login_users is defined and inventory_hostname in groups['kerberosauthclients']

- include: auth.yml
  when: inventory_hostname in groups['kerberosauthclients']
