grt_group: grt
grt_user: grt
grt_dir: /opt/galactic-radio-telescope

grt_version: master
grt_force_checkout: true

grt_create_group: true
grt_create_user: true

grt_upload_dir: "{{ grt_dir }}/uploads"
grt_queries_dir: "{{ grt_dir }}/queries"
