---

- name: Install CernVM-FS local proxy dependencies (yum)
  yum:
    name: "{{ item }}"
  with_items:
    - squid
  when: ansible_os_family == "RedHat"

- name: Install CernVM-FS local proxy dependencies (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - squid
  when: ansible_os_family == "Debian"

# stratum1s are pulling double duty as local proxies for now
- name: Create squid hosts file
  copy:
    content: |
      {{ inventory_hostname }} 127.0.0.1
    dest: /etc/squid/hosts
  notify:
    - restart squid

- name: Configure squid for local proxies
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    backup: yes
  notify:
    - restart squid

- name: Ensure squid is enabled and running
  service:
    name: squid
    state: started
    enabled: yes
