---

- name: Install CernVM-FS server and dependencies (yum)
  yum:
    name: "{{ item }}"
  with_items:
    - httpd
    - mod_wsgi
    - squid
    - cvmfs-server
    - cvmfs-config
  when: ansible_os_family == "RedHat"

- name: Install CernVM-FS server and dependencies (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - apache2
    - cvmfs-server
    - cvmfs-config
  when: ansible_os_family == "Debian"

- name: Install CernVM-FS keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0444"
  with_items: "{{ cvmfs_keys }}"

- name: Change Apache listen port
  lineinfile:
    # FIXME: RHEL-specific
    dest: /etc/httpd/conf/httpd.conf
    line: "Listen {{ cvmfs_stratum1_apache_port }}"
    regexp: "^Listen\\s+"
    backup: yes
  notify:
    - reload apache

- name: Ensure Apache is enabled and running
  service:
    # FIXME: RHEL-specific
    name: httpd
    state: started
    enabled: yes

- name: Configure squid for stratum 1 proxy
  template:
    src: stratum1_squid.conf.j2
    dest: /etc/squid/squid.conf
    backup: yes
  notify:
    - restart squid

- name: Ensure squid is enabled and started
  service:
    name: squid
    state: started
    enabled: yes

- name: Ensure replicas are configured
  command: /usr/bin/cvmfs_server add-replica -z -o root http://{{ item.stratum0 }}/cvmfs/{{ item.repository }} /etc/cvmfs/keys/{{ item.repository }}.pub
  args:
    creates: /etc/cvmfs/repositories.d/{{ item.repository }}
  with_items: "{{ cvmfs_repositories }}"
  notify:
    - restart apache

- name: Schedule stratum1 snapshots
  cron:
    name: cvmfs_snapshot_{{ item.repository }}
    cron_file: ansible_cvmfs_stratum1_snapshot
    job: /usr/bin/cvmfs_server snapshot {{ item.repository }}
    minute: 0,15,30,45
    user: root
  with_items: "{{ cvmfs_repositories }}"
