---
- name: Tasks for "base environment" hosts
  hosts: infrastructure
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - geerlingguy.pip
    - dj-wasabi.telegraf
    - jnv.unattended-upgrades
