---
- name: Tasks for "jenkins" hosts
  hosts: build01
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    #- geerlingguy.repo-epel
    #- influxdata.chrony
    - linuxhq.yum_cron
    - hxr.admin-tools
    #- geerlingguy.nginx
    #- role: geerlingguy.java
      #java_packages:
      #- java-1.8.0-openjdk

    #- geerlingguy.jenkins
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
