---
- name: Tasks for "jenkins" hosts
  hosts: build
  become: true
  vars:
    hostname: build.galaxyproject.eu
  vars_files:
    - "secret_group_vars/jenkins.yml"
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - influxdata.chrony
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    - dj-wasabi.telegraf
    - hxr.autofs-format-n-mount
    # CUSTOM
    - geerlingguy.java
    - geerlingguy.jenkins
    - hxr.jenkins-extra
    ## END CUSTOM
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
