---
- name: Celery cluster
  hosts: celerycluster
  become: true
  become_user: root

  pre_tasks:
    - name: Disable htcondor service
      ansible.builtin.service:
        name: condor
        enabled: false
        state: stopped

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_kernel_5: true
        enable_install_software: true
    - influxdata.chrony

    ## Filesystems
    - usegalaxy-eu.autofs     # Set up the mount points which will be needed later
    - usegalaxy_eu.galaxy_systemd
