---
- name: Tasks for "centos" hosts
  hosts: centos
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.repo-epel
    - linuxhq.yum-cron
    - hxr.admin-tools
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
