- name: Deploy CVMFS Stratum 1 on bwCloud OpenStack
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    server_names:
      - cvmfs1-ufr0.usegalaxy.eu
    server:
        flavor: m1.small
        nics:
          - net-name=public2
          - net-name=galaxy-net
        security_groups:
          - egress
          - public-ping
          - public-web
          - public-ssh
  vars_files:
    - "secret_group_vars/all.yml"

  roles:
    - hxr.bwcloud
