---
- name: Tasks for "docker" hosts
  hosts: docker
  become: true
  tags: docker
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - dev-sec.os-hardening
    #- dev-sec.ssh-hardening
    - geerlingguy.pip
    - geerlingguy.docker
