---
- hosts: ftp
  become: true
  vars:
    hostname: ftp.usegalaxy.eu
  vars_files:
    - "secret_group_vars/ftp.yml"
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.admin-tools
    - linuxhq.yum-cron
    - hxr.autofs
    - geerlingguy.nginx
    # Remap 999:999 to other ids.
    - hxr.remap-user
    # Now add custom galaxy user with hardcoded ID. The user info is in group_vars/ftp.yml
    - hxr.replace-galaxy-user
    - galaxyprojectdotorg.proftpd
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - multinic
