- name: Deploy ftp server on bwCloud OpenStack
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    server_names:
      - ftp.usegalaxy.eu
    server:
        image: "ubuntu-16.04-multinic"
        flavor: m1.small
        nics:
          - net-name=public-new
        security_groups:
          - egress
          - Public
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hxr.bwcloud
