---
- name: galaxy
  hosts: galaxy
  become: true
  become_user: root
  vars:
    hostname: sn04.bi.uni-freiburg.de
  vars_files:
    - "secret_group_vars/all.yml"
  pre_tasks:
    # TODO(hxr): fails due to nginx user not available yet.
    #- name: Create nginx cache dir
      #file:
          #path: /var/cache/nginx/static
          #state: directory
          #owner: nginx
          #group: root
          #mode: 0700
    #- name: Create Galaxy runtime user
      #user:
        #name: galaxy
        #comment: "Galaxy Server"
        #system: yes
        #home: /opt/galaxy
        #createhome: yes
        #uid: 999
      #become: yes
    - name: Install Dependencies
      package:
        name: ['git', 'python-psycopg2', 'python-virtualenv', 'bc']
      become: yes
  roles:
    #- hxr.galaxy-user
    #- geerlingguy.docker
    ## TODO(hxr): fails whenever galaxy homedir is created without bashrc
    #- role: hxr.docker-ssl-client
      #vars:
        #docker_account: galaxy
    #- geerlingguy.repo-epel
    #- hxr.exclude-repo # Exclude epel repos for condor, node, npm
    #- geerlingguy.nodejs
    # TODO(hxr): missing gxmnt etc
    - hxr.monitor-cluster
    - role: hxr.galaxy-cron
      become: yes
      become_user: galaxy
    - hxr.galaxy-nonreproducible-tools
    - hxr.galaxy-misc
    #- hxr.autofs
    #- cvmfs
    #- dynmotd
    #- ssh-host-sign
    #- hxr.admin-tools
    #- hxr.monitor-email
    #- htcondor
    #- linuxhq.yum_cron
    #- influxdata.chrony
    # TODO(hxr): maybe don't run on temp testing VMs?
    #- hxr.certbot

    # GALAXY
    #- hxr.postgres-connection
    #- gxadmin
    #- packages
    #- hxr.galaxy-log-dir
    # TODO(hxr): /var/log/galaxy doesn't exist
    #- supervisor
    #- role: hxr.install-to-venv
      #become: yes
      #become_user: galaxy
    #- geerlingguy.nginx
    #- hxr.tiaas
    - role: usegalaxy_privileged
      become: yes
      become_user: galaxy
    - role: galaxyproject.galaxy
      become: yes
      become_user: galaxy
    # TODO: cannot come before galaxy
    - role: hxr.welcome_pages
      become: yes
      become_user: galaxy
    - role: galaxyproject.interactive_environments
      become: yes
      become_user: galaxy

    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
