---
# TODO:
# - atop service not ednaled
- name: galaxy
  hosts: galaxy
  become: true
  become_user: root
  vars:
    hostname: sn04.bi.uni-freiburg.de
  vars_files:
    - group_vars/tiaas.yml
    - group_vars/custom-sites.yml
    - group_vars/gxconfig.yml
    - secret_group_vars/all.yml
  handlers:
    - name: Restart Galaxy
      shell: source /opt/galaxy/.bashrc && /usr/bin/gxadmin handler restart && /usr/bin/gxadmin zerg swap
  pre_tasks:
    # TODO(hxr): fails due to nginx user not available yet.
    #- name: Install Dependencies
      #package:
        #name: ['git', 'python-psycopg2', 'python-virtualenv', 'bc']
      #become: yes
  roles:
    - hxr.tiaas
    #- hxr.galaxy-user
    #- geerlingguy.docker
    ## TODO(hxr): fails whenever galaxy homedir is created without bashrc
    #- role: hxr.docker-ssl-client
      #vars:
        #docker_account: galaxy
    #- geerlingguy.repo-epel
    #- hxr.exclude-repo # Exclude epel repos for condor, node, npm
    #- geerlingguy.nodejs
    ## TODO(hxr): fix ordering of these
    - hxr.monitor-cluster
    - hxr.monitor-galaxy
    ## TODO(hxr): missing gxmnt etc
    - role: hxr.galaxy-cron
      become: yes
      become_user: galaxy
    - role: hxr.galaxy-nonreproducible-tools
      become: yes
      become_user: galaxy
    - hxr.galaxy-misc
    - hxr.autofs
    - cvmfs
    - dynmotd
    #- ssh-host-sign
    - hxr.admin-tools
    - hxr.monitor-email
    #- htcondor
    - linuxhq.yum_cron
    - influxdata.chrony
    ## TODO(hxr): maybe don't run on temp testing VMs?
    ##- hxr.certbot

    ## GALAXY
    - role: hxr.postgres-connection
      become: yes
      become_user: galaxy
    - usegalaxy-eu.gxadmin
    - hxr.galaxy-log-dir
    ## TODO(hxr): /var/log/galaxy doesn't exist
    - packages
    - supervisor
    #- hxr.install-to-venv
    - geerlingguy.nginx
    - hxr.tiaas
    # The real galayx role
    - role: galaxyproject.galaxy
      become: yes
      become_user: galaxy
    # The alternate setup for testing.
    # These cannot come before galaxy
    - hxr.welcome_pages
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening


    #- role: galaxyproject.galaxy
    #  become: yes
    #  become_user: galaxy
    #  vars:
    #    galaxy_server_dir: "{{ galaxy_root }}/server-19.01"
    #    galaxy_create_user: false
    #    galaxy_manage_paths: true
    #    galaxy_manage_clone: true
    #    galaxy_manage_static_setup: true
    #    galaxy_manage_mutable_setup: false
    #    galaxy_manage_database: false
    #    galaxy_instance_codename: test
    #    galaxy_host_codename: test
    #    galaxy_fetch_dependencies: true
    #    galaxy_build_client: false
    #    galaxy_commit_id: release_19.01_europe
    #    galaxy_force_checkout: true
    #    galaxy_config_file_src_dir: "files/galaxy-19.01"
    #    galaxy_config_template_src_dir: "templates/galaxy-19.01"
    #    galaxy_server_dir: "{{ galaxy_root }}/server-19.01"
    #    galaxy_venv_dir: "{{ galaxy_root }}/venv-19.01"
    #    galaxy_config_dir: "{{ galaxy_root }}/config-19.01"
    #    galaxy_mutable_config_dir: "{{ galaxy_root }}/mutable-config-19.01"
    #    galaxy_mutable_data_dir: "{{ galaxy_root }}/mutable-data-19.01"
