---
- name: galaxy
  hosts: galaxy
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - hxr.vault
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - linuxhq.yum-cron
    - influxdata.chrony
    #- hxr.galaxy-echo-tool
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
