---
- name: galaxy
  hosts: galaxy
  vars:
    hostname: sn04.bi.uni-freiburg.de
  vars_files:
    - "secret_group_vars/all.yml"
  pre_tasks:
    - name: Create Galaxy runtime user
      user:
        name: galaxy
        comment: "Galaxy Server"
        system: yes
        home: /opt/galaxy
        createhome: yes
        uid: 999
      become: yes
    - name: Install Dependencies
      package:
        name: "{{ item }}"
      become: yes
      with_items:
        - git
        - python-psycopg2
        - python-virtualenv
        - nodejs
        - npm
  roles:
    #- geerlingguy.repo-epel
    #- hxr.autofs
    #- cvmfs
    #- dynmotd
    #- ssh-host-sign
    #- hxr.admin-tools
    #- hxr.monitor-email
    #- htcondor
    #- linuxhq.yum-cron
    #- influxdata.chrony
    #- hxr.certbot
    # galaxy
    #- packages
    #- supervisor
    #- geerlingguy.nginx
    - role: hxr.welcome_pages
      become: yes
      become_user: galaxy
    - role: galaxyproject.interactive_environments
      become: yes
      become_user: galaxy
    - role: galaxyproject.galaxy
      become: yes
      become_user: galaxy
    #
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
