---
- name: Test.UseGalaxy.eu
  hosts: galaxy-test
  become: true
  become_user: root
  vars:
    hostname: test.internal.usegalaxy.eu
  vars_files:
    - group_vars/custom-sites.yml
    - group_vars/gxconfig-test.yml
    - secret_group_vars/all.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'python-psycopg2', 'python-virtualenv', 'bc']
      become: yes
  roles:
    - geerlingguy.docker
    ### TODO(hxr): fails whenever galaxy homedir is created without bashrc
    #- role: hxr.docker-ssl-client
      #vars:
        #docker_account: galaxy
    - geerlingguy.repo-epel
    - hxr.exclude-repo # Exclude epel repos for condor, node, npm
    ## TODO(hxr): fix ordering of these
    - hxr.monitor-cluster
    ## TODO(hxr): missing gxmnt etc
    - role: hxr.galaxy-cron
      become: yes
      become_user: galaxy
    #- role: hxr.galaxy-nonreproducible-tools
      #become: yes
      #become_user: galaxy
    - hxr.galaxy-misc
    #- hxr.autofs
    - cvmfs
    - usegalaxy-eu.dynmotd
    - ssh-host-sign
    - hxr.admin-tools
    - hxr.monitor-email
    - linuxhq.yum_cron
    - influxdata.chrony
    ## TODO(hxr): maybe don't run on temp testing VMs?
    ##- usegalaxy-eu.certbot

    ## GALAXY
    - role: hxr.postgres-connection
      become: yes
      become_user: galaxy
    - usegalaxy-eu.gxadmin
    - packages
    - usegalaxy-eu.galaxy-systemd
    - hxr.install-to-venv
    - geerlingguy.nginx
    # The real galaxy role
    - role: galaxyproject.galaxy
      become: yes
      become_user: galaxy
    - hxr.welcome_pages
    - dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
