---
- name: galaxy
  hosts: galaxy
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    #- geerlingguy.repo-epel
    #- hxr.admin-tools
    - cvmfs
    - linuxhq.yum-cron
    - influxdata.chrony
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
