---
- name: Test.UseGalaxy.eu
  hosts: galaxy-test
  become: true
  become_user: root
  vars:
    hostname: test.internal.usegalaxy.eu
  vars_files:
    - group_vars/tiaas-test.yml
    - group_vars/custom-sites.yml
    - group_vars/gxconfig-test.yml
    - secret_group_vars/elixir_aai.yml
    - secret_group_vars/test-db.yml
    - secret_group_vars/all.yml
  handlers:
    - name: Restart Galaxy
      shell: 'source /opt/galaxy/.bashrc && systemctl restart galaxy-zergling@* galaxy-handler@*'
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'python-psycopg2', 'python-virtualenv', 'bc']
      become: yes
  roles:
    # Normally we set hostname here, but we get an error so it is commented out:
    #     err=Could not get property: Failed to activate service 'org.freedesktop.hostname1': timed out
    #- hostname
    - usegalaxy-eu.dynmotd
    # Install EPEL
    - geerlingguy.repo-epel
    # We want to exclude a couple of packages as we will fetch those
    # dependencies from other repos: condor, node/npm
    - hxr.exclude-repo
    - linuxhq.yum_cron
    - hxr.admin-tools
    - influxdata.chrony
    # Setup the mount points which will be needed later
    - hxr.autofs
    - galaxyproject.cvmfs
    # Monitoring
    - hxr.monitor-cluster
    - hxr.monitor-email
    - dj-wasabi.telegraf

    # Setup Galaxy user
    - role: galaxyproject.galaxy
      vars:
        galaxy_create_user: yes
        galaxy_manage_clone: no
        galaxy_manage_static_setup: no
        galaxy_manage_mutable_setup: no
        galaxy_manage_database: no
        galaxy_fetch_dependencies: no
        galaxy_build_client: no
    # The bashrc needs to be created for several later features.
    - role: usegalaxy-eu.bashrc
      become_user: galaxy

    ## Setup docker
    - geerlingguy.docker
    - role: hxr.docker-ssl-client
      become_user: galaxy

    # HTCondor Cluster setup
    - htcondor

    # Misc.
    - role: hxr.galaxy-cron
      become: yes
      become_user: galaxy
    - role: hxr.galaxy-nonreproducible-tools
      become: yes
      become_user: galaxy
    - hxr.galaxy-misc
    - usegalaxy-eu.dynmotd

    ## SSL / Security
    # Sign the server host key to prevent TOFU for SSH
    - ssh-host-sign
    # Setup the AWS client that will be needed for route53 authentication of certbot
    - hxr.aws-cli

    ## GALAXY
    - role: hxr.postgres-connection
      become_user: galaxy
    - usegalaxy-eu.gxadmin
    # TODO move under monitoring + telegraf.
    - usegalaxy-eu.galaxy-slurp

    # TODO(hxr): nginx role doesn't create nginx_proxy_cache_path
    - geerlingguy.nginx
    - hxr.tiaas
    # The real galaxy role
    - galaxyproject.galaxy
    - hxr.install-to-venv
    # Manage the Galaxy processes with SystemD
    - usegalaxy-eu.galaxy-systemd
    # Setup the NodeJS proxy (depends on NodeJS being already available)
    - usegalaxy-eu.gie-node-proxy
    # Deploy the GIE configuration
    - usegalaxy-eu.gie-deployer
    - usegalaxy-eu.subdomain-themes
    - usegalaxy-eu.limits

    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
