---
- name: Test.UseGalaxy.eu
  hosts: galaxy-test
  become: true
  become_user: root
  vars:
    hostname: test.internal.usegalaxy.eu
  vars_files:
    - group_vars/tiaas-test.yml
    - group_vars/custom-sites.yml
    - group_vars/gxconfig-test.yml
    - secret_group_vars/elixir_aai.yml
    - secret_group_vars/all.yml
  handlers:
    - name: Restart Galaxy
      shell: 'source /opt/galaxy/.bashrc && systemctl restart galaxy-zergling@* galaxy-handler@*'
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'python-psycopg2', 'python-virtualenv', 'bc']
      become: yes
  roles:
    - hostname
    - geerlingguy.docker
    ## TODO(hxr): fails whenever galaxy homedir is created without bashrc
    #- role: hxr.docker-ssl-client
      #vars:
        #docker_account: galaxy
    - geerlingguy.repo-epel
    - hxr.exclude-repo # Exclude epel repos for condor, node, npm
    ## TODO(hxr): fix ordering of these
    - hxr.monitor-cluster
    ## TODO(hxr): missing gxmnt etc
    - role: hxr.galaxy-cron
      become: yes
      become_user: galaxy
    - role: hxr.galaxy-nonreproducible-tools
      become: yes
      become_user: galaxy
    - hxr.galaxy-misc
    - hxr.autofs
    - cvmfs
    - usegalaxy-eu.dynmotd
    - ssh-host-sign
    - hxr.admin-tools
    - hxr.monitor-email
    - htcondor
    - linuxhq.yum_cron
    - influxdata.chrony
    - hxr.aws-cli

    ## GALAXY
    - role: hxr.postgres-connection
      vars:
        pg_owner: telegraf
        pg_group: telegraf
    - role: hxr.postgres-connection
      vars:
        pg_owner: galaxy
        pg_group: galaxy
    - usegalaxy-eu.gxadmin
    - usegalaxy-eu.galaxy-slurp
    - packages
    - hxr.install-to-venv
    # TODO(hxr): nginx role doesn't create nginx_proxy_cache_path
    - geerlingguy.nginx
    - hxr.tiaas
    # The real galaxy role
    - role: galaxyproject.galaxy
      become: yes
      become_user: galaxy
    # These cannot come before galaxy
    - usegalaxy-eu.galaxy-systemd
    - hxr.welcome_pages
    - dj-wasabi.telegraf
    - usegalaxy-eu.limits
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
