- name: Deploy
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    server_names:
      - stats.usegalaxy.eu
    server:
        flavor: m1.large
        nics:
          - net-name=public
        security_groups:
          - egress
          - public-ping
          - public-web
          - public-ssh
  vars_files:
    - "secret_group_vars/all.yml"

  roles:
    - hxr.bwcloud
