---
- name: Grafana
  hosts: grafana
  become: true
  vars:
    hostname: stats.galaxyproject.eu
  vars_files:
    - group_vars/grafana-gitter-bridge.yml
    - secret_group_vars/all.yml
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - hxr.monitor-ssl
    - linuxhq.yum_cron
    - galaxyproject.nginx
    #- hxr.autofs-format-n-mount
    # Custom
    #- hxr.simple-nagios
    - cloudalchemy.grafana
    - pgs
    - hxr.grafana-gitter-bridge
    # End Custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
