---
- name: Tasks for "grafana" hosts
  hosts: grafana
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  vars:
    hostname: stats.new.usegalaxy.eu
  roles:
    - hostname
    - dynmotd
    - ssh-host-sign
    - influxdata.chrony
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - hxr.monitor-email
    - linuxhq.yum-cron
    - geerlingguy.nginx
    # Custom
    - hxr.simple-nagios
    - picotrading.ansible-grafana
    - pgs
    # End Custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
