---
- hosts: grafana
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  vars:
    hostname: stats.galaxyproject.eu
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    # Custom
    #- hxr.simple-nagios
    - cloudalchemy.grafana
    - pgs
    # End Custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
