---
- name: Tasks for "grafana" hosts
  hosts: grafana
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  vars:
    hostname: stats.usegalaxy.eu
  roles:
    - hostname
    - hxr.vault
    - influxdata.chrony
    - hxr.certbot
    - hxr.admin-tools
    - geerlingguy.nginx
    - hxr.simple-nagios
    - picotrading.ansible-grafana
    #- pgs
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
