---
- name: Tasks for "grafana" hosts
  hosts: grafana
  become: true
  vars_files:
    - "secret_group_vars/pgs.yml"
    - "secret_group_vars/grafana.yml"
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  vars:
    hostname: stats.usegalaxy.eu
    certbot_auto_renew: yes
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: 10
    certbot_auto_renew_minute: 59

    certbot_environment: production #staging
    certbot_domains:
      - stats.usegalaxy.eu
    certbot_agree_tos: --agree-tos
    certbot_admin_email: security@usegalaxy.eu
  roles:
    - hostname
    #- geerlingguy.repo-epel
    - hxr.certbot
    #- hxr.admin-tools
    - hxr.simple-nagios
    - picotrading.ansible-grafana
    - pgs
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
