---
- name: Haproxy
  hosts: haproxy
  become: true
  vars:
    hostname: proxy.usegalaxy.eu
    server_names:
      - usegalaxy.eu
      - proxy.usegalaxy.eu
      - hicexplorer.usegalaxy.eu
    certbot_auto_renew: yes
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: 10
    certbot_auto_renew_minute: 59
    certbot_auto_renew_extra: "--http-01-port 63443"

    certbot_environment: production #staging
    certbot_domains:
      - usegalaxy.eu
      - proxy.usegalaxy.eu
      - hicexplorer.usegalaxy.eu
    certbot_agree_tos: --agree-tos
    certbot_admin_email: security@usegalaxy.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - linuxhq.yum-cron
    - hxr.dns
    - hostname
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.admin-tools
    - geerlingguy.haproxy
    - hxr.haproxy-error-pages
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
