---
- name: Haproxy
  hosts: haproxy
  become: true
  vars:
    hostname: proxy.galaxyproject.eu
    server_names:
      - 'usegalaxy.eu'
      - '*.usegalaxy.eu'
      - 'usegalaxy.de'
      - '*.usegalaxy.de'
      - 'galaxyproject.eu'
      - '*.galaxyproject.eu'
  vars_files:
    - "group_vars/custom-sites.yml"
    - "secret_group_vars/all.yml"
  roles:
    #- hostname
    #- linuxhq.yum_cron
    #- geerlingguy.repo-epel
    #- hxr.admin-tools
    #- hxr.aws-cli
    #- hxr.certbot
    # TODO(hxr): find downloader script
    #- hxr.haproxy-error-pages
    # TODO(hxr): allow connections to localohst for haproxy (selinux)
    # add to group or swap to new certbot role.
    - geerlingguy.haproxy
    - jasonroyle.rabbitmq
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
