---
- hosts: haproxy
  become: true
  tags: haproxy
  tasks:
   - hostname:
       name: proxy.usegalaxy.eu
  roles:
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - geerlingguy.haproxy
