---
- name: Haproxy
  hosts: haproxy
  become: true
  vars:
    hostname: proxy.galaxyproject.eu
    server_names:
      - 'usegalaxy.eu'
      - '*.usegalaxy.eu'
      - 'usegalaxy.de'
      - '*.usegalaxy.de'
      - 'galaxyproject.eu'
      - '*.galaxyproject.eu'
    certbot_auto_renew: yes
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: 10
    certbot_auto_renew_minute: 59
    certbot_auto_renew_extra: "--dns-route53"
    certbot_post_renewal: |
        # Haproxy is weird and needs the full chain + privkey in a single file.
        cat /etc/ssl/certs/fullchain.pem       > /etc/pki/tls/private/full.pem
        cat /etc/ssl/private/privkey.pem  >> /etc/pki/tls/private/full.pem
        chown root:ssl-cert /etc/pki/tls/private/full.pem
        systemctl reload haproxy || true
        systemctl restart rabbitmq-server || true

    certbot_environment: production #staging
    certbot_domains: "{{ server_names }}"
    certbot_agree_tos: --agree-tos
    certbot_admin_email: security@usegalaxy.eu
  vars_files:
    - "group_vars/custom-sites.yml"
    - "secret_group_vars/all.yml"
  roles:
    #- hostname
    #- linuxhq.yum_cron
    #- geerlingguy.repo-epel
    #- hxr.admin-tools
    #- hxr.aws-cli
    #- hxr.certbot
    # TODO(hxr): find downloader script
    #- hxr.haproxy-error-pages
    - geerlingguy.haproxy
    - jasonroyle.rabbitmq
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
