---
- name: Haproxy
  hosts: haproxy
  become: true
  vars:
    hostname: proxy.galaxyproject.eu
    server_names:
      - proxy.usegalaxy.eu
      # Galaxy
      - usegalaxy.eu
      # Galaxy aliases
      - hicexplorer.usegalaxy.eu
      - static.usegalaxy.eu
      - metagenomics.usegalaxy.eu
      - rna.usegalaxy.eu
      - ecology.usegalaxy.eu
      - proteomics.usegalaxy.eu
      - xn--cw8h.usegalaxy.eu
      - xn--ls8h.usegalaxy.eu
      - xn--2n8h.usegalaxy.eu
      # other services
      - stats.galaxyproject.eu
      - build.galaxyproject.eu
      - influxdb.galaxyproject.eu
      - apollo.usegalaxy.eu # this one must be under here for the cookie auth magic.
      # Intentionally NOT on this list:
      #  cvmfs1-ufr0.galaxyproject.eu
      #  ftp.usegalaxy.eu
    server_names_de:
      - usegalaxy.de
    certbot_auto_renew: yes
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: 10
    certbot_auto_renew_minute: 59
    certbot_auto_renew_extra: "--preferred-challenges http-01 --http-01-port 8118"

    certbot_environment: production #staging
    certbot_domains: "{{ server_names }}"
    certbot_agree_tos: --agree-tos
    certbot_admin_email: security@usegalaxy.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hxr.dns
    - hostname
    - linuxhq.yum-cron
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.admin-tools
    - geerlingguy.haproxy
    - hxr.haproxy-error-pages
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - jasonroyle.rabbitmq
