---
- hosts: influxdb
  become: true
  vars:
    hostname: influxdb.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - hxr.admin-tools
    - influxdata.chrony
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.monitor-email
    - linuxhq.yum-cron
    - geerlingguy.nginx
    - hxr.autofs
    # BEGIN custom
    - mtchavez.influxdb
    - hxr.influxdb
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
