---
- name: Tasks for "influxdb" hosts
  hosts: influxdb
  become: true
  vars:
    influxdb_base_data_dir: /data/influxdata
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - mtchavez.influxdb
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
