---
- name: Tasks for "influxdb" hosts
  hosts: influxdb
  become: true
  vars:
    hostname: influxdb.usegalaxy.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    #- hostname
    #- geerlingguy.repo-epel
    #- hxr.certbot
    #- hxr.admin-tools
    #- linuxhq.yum-cron
    #- multinic
    #- hxr.autofs
    #- geerlingguy.nginx
    # BEGIN custom
    #- mtchavez.influxdb
    - hxr.influxdb
    # END custom
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
