---
- name: Tasks for "jenkins" hosts
  hosts: jenkins 
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - dj-wasabi.telegraf
    - jnv.unattended-upgrades
    - dev-sec.os-hardening
    #- dev-sec.ssh-hardening
