---
- name: Multinic
  hosts: multinic
  become: true
  vars:
    hostname: multinic.usegalaxy.eu
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - multinic
    - hostname
    - geerlingguy.repo-epel
    - hxr.admin-tools
