---

- name: Get EC2 Facts
  hosts: ec2hosts
  remote_user: root
  tasks:
    - name: Get EC2 Facts
      action: ec2_facts
  tags: always

- name: Tasks for all hosts
  hosts: all
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_group_vars/all.yml"
    - [ "{{ deploy_env }}/secret_host_vars/{{ inventory_hostname }}.yml", "{{ deploy_env }}/secret_host_vars/default.yml" ]
  roles:
    - role: requiretty        # Disable requiretty for Ansible ssh pipelining
      tags: initial,requiretty
    - role: remote_management # Set up IPMI/serial stuff
      tags: initial,remote_management
    - role: ssh               # Enable password auth and root logins
      tags: initial,ssh
    - role: timezone          # Configure system timezone
      tags: initial,timezone
    - role: resolv            # Set resolv.conf for static hosts
      tags: initial,resolv
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: postfix           # MX and null client configuration
      tags: mail,postfix
    - role: mailman           # Mailing lists
      tags: mail,mailman
      when: "'listservers' in group_names"
  tags: initial

- name: Tasks for jenkins hosts
  hosts: jenkinsservers
  remote_user: root
  roles:
    - role: linuxbrew        # Install linuxbrew
      tags: linuxbrew
  tags: initial

# This is here because it's currently due to a SmartOS issue:
# https://github.com/joyent/smartos-live/issues/469
# If that issue is fixed, it should be possible to remove this and undo
# explicitly setting the sys_fs_import priv
- name: Assign the sys_fs_import privilege to backup users
  hosts: zfsbackupservers
  remote_user: root
  vars:
    backupusers:
      - zfsdump-orval
  tasks:
    - name: "Set sys_fs_import for backup users"
      lineinfile:
        dest: /etc/user_attr
        backup: "yes"
        line: "{{ item }}::::type=normal;defaultpriv=basic,sys_fs_import"
        regexp: "^{{ item }}:.*"
      with_items: backupusers
