---
- name: Proxy internal
  hosts: proxy-internal
  become: true
  vars:
    hostname: proxy.internal.galaxyproject.eu
  vars_files:
    - secret_group_vars/pulsar.yml     # Pulsar + MQ Connections
    - secret_group_vars/all.yml
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-tools
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    - jasonroyle.rabbitmq
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
