- src: dev-sec.os-hardening
  version: 4.2.0
- src: dev-sec.ssh-hardening
  version: 4.3.1
- src: devops.tomcat7
  version: 1.0.0
- src: dj-wasabi.telegraf
  version: 0.10.0
- src: galaxyproject.galaxy
  version: 0.8.3
- src: galaxyproject.proftpd
  version: 0.2.4
- src: galaxyproject.nginx
  version: 0.6.0
- src: galaxyproject.postgresql
  version: 1.0.1
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.gitlab
  version: 2.5.1
- src: geerlingguy.haproxy
  version: 1.1.1
- src: geerlingguy.java
  versoin: 1.9.5
- src: geerlingguy.jenkins
  version: 3.2.0
- src: geerlingguy.nfs
  version: 1.2.3
- src: geerlingguy.nginx
  version: 2.5.0
- src: geerlingguy.nodejs
  version: 4.2.2
- src: geerlingguy.pip
  version: 1.0.0
- src: geerlingguy.repo-epel
  version: 1.2.2
- src: influxdata.chrony
  version: master
- src: jasonroyle.rabbitmq
  version: 0.0.4
- src: linuxhq.yum_cron
  version: master
- src: mtchavez.influxdb
  version: v6.0.0
- src: picotrading.ansible-grafana
  version: master
- src: https://github.com/usegalaxy-eu/ansible-gxadmin
  name: usegalaxy-eu.gxadmin
  version: 3ce9bfdec134b32b9f3a5c648ffba8f64fb17c5f
- src: https://github.com/usegalaxy-eu/ansible-certbot
  name: usegalaxy-eu.certbot
  version: master
- src: https://github.com/usegalaxy-eu/ansible-galaxy-systemd
  name: usegalaxy-eu.galaxy-systemd
  version: master
- src: https://github.com/usegalaxy-eu/ansible-dynmotd
  name: usegalaxy-eu.dynmotd
  version: master
