---
- hosts: sentry
  become: true
  vars:
    hostname: sentry.galaxyproject.eu
    pip_install_packages:
      - name: docker
      - name: docker-compose
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    #- hostname
    #- hxr.admin-tools
    #- influxdata.chrony
    #- geerlingguy.repo-epel
    #- hxr.certbot
    #- hxr.monitor-email
    #- linuxhq.yum-cron
    #- geerlingguy.nginx
    #- hxr.autofs
    #- geerlingguy.pip
    #- geerlingguy.docker
    - hxr.sentry
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
