- name: Deploy on bwCloud OpenStack
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    server_names:
      - sentry.usegalaxy.eu
    server:
        flavor: m1.large
        nics:
          - net-name=public
          - net-name=galaxy-net
        security_groups:
          - egress
          - public-ping
          - public-web
          - public-ssh
  vars_files:
    - "secret_group_vars/all.yml"

  roles:
    - hxr.bwcloud
