---
- name: Sentry
  hosts: sentry
  become: true
  vars:
    hostname: sentry.usegalaxy.eu
    pip_install_packages:
      - name: docker
      - name: docker-compose
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - hxr.vault
    - multinic
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.admin-tools
    - hxr.email
    - linuxhq.yum-cron
    - hxr.autofs
    - geerlingguy.nginx
    - geerlingguy.pip
    - geerlingguy.docker
    # Remap 999:999 to other ids.
    - hxr.remap-user
    - hxr.replace-galaxy-user
    # Finally safe to install sentry stuff
    - hxr.sentry
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
