---
- hosts: telescope
  become: true
  vars:
    hostname: telescope.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - hxr.admin-tools
    - influxdata.chrony
    - geerlingguy.repo-epel
    - hxr.certbot
    - hxr.monitor-email
    - linuxhq.yum_cron
    - geerlingguy.nginx
    - hxr.autofs
    # BEGIN custom
    - geerlingguy.pip
    - geerlingguy.docker
    - hxr.radio-telescope
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
