---
- name: Telescope
  hosts: telescope
  become: true
  vars:
    hostname: telescope.galaxyproject.org
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - hostname
    - hxr.vault
    - hxr.admin-tools
    - dj-wasabi.telegraf
    - jnv.unattended-upgrades
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
