---
- name: Telescope
  hosts: telescope
  become: true
  vars:
    hostname: telescope.galaxyproject.org
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - hxr.admin-tools
    - dj-wasabi.telegraf
    - jnv.unattended-upgrades
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
