- name: Deploy MANY server on bwCloud OpenStack
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - "secret_group_vars/all.yml"
  tasks:
    - name: Deploy the instance
      os_server:
        state: present
        name: "{{ item }}"
        image: 'CentOS Server 7 RAW'
        key_name: cloud2
        flavor: m1.small
        nics:
          - net-name=public-new
        security_groups:
          - egress
          - public-ping
          - public-web
          - public-ssh
      with_items:
        - 0.test.usegalaxy.eu
        - 1.test.usegalaxy.eu
        - 2.test.usegalaxy.eu
        - 3.test.usegalaxy.eu
        - 4.test.usegalaxy.eu
        - 5.test.usegalaxy.eu
        - 6.test.usegalaxy.eu
        - 7.test.usegalaxy.eu
        - 8.test.usegalaxy.eu
        - 9.test.usegalaxy.eu
        - 10.test.usegalaxy.eu
        - 11.test.usegalaxy.eu
        - 12.test.usegalaxy.eu
        - 13.test.usegalaxy.eu
        - 14.test.usegalaxy.eu
        - 15.test.usegalaxy.eu
        - 16.test.usegalaxy.eu
        - 17.test.usegalaxy.eu
        - 18.test.usegalaxy.eu
        - 19.test.usegalaxy.eu
        - 20.test.usegalaxy.eu
        - 21.test.usegalaxy.eu
        - 22.test.usegalaxy.eu
        - 23.test.usegalaxy.eu
        - 24.test.usegalaxy.eu
        - 25.test.usegalaxy.eu
        - 26.test.usegalaxy.eu
        - 27.test.usegalaxy.eu
        - 28.test.usegalaxy.eu
        - 29.test.usegalaxy.eu
