---
- name: Install and configure tusd
  hosts: upload
  become: true
  become_user: root
  vars:
    tusd_instances:
      - name: test_uploads
        # user that tusd will run as
        user: "{{ galaxy_user.name }}"
        # group that tusd will run as
        group: "{{ galaxy_group.name }}"
        # args passed to tusd
        args:
          - -host=upload.galaxyproject.eu
          - -port=1080
          - -upload-dir=/data/dnb01/galaxy_db/tmp
          - -hooks-http=https://test.usegalaxy.eu/api/upload/hooks
          - -hooks-http-forward-headers=X-Api-Key,Cookie
      - name: main_uploads
        # user that tusd will run as
        user: "{{ galaxy_user.name }}"
        # group that tusd will run as
        group: "{{ galaxy_group.name }}"
        # args passed to tusd
        args:
          - -host=upload.galaxyproject.eu
          - -port=1081
          - -upload-dir=/data/jwd/tmp
          - -hooks-http=https://usegalaxy.eu/api/upload/hooks
          - -hooks-http-forward-headers=X-Api-Key,Cookie

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
        enable_kernel_5: true
        enable_install_software: true
    - usegalaxy-eu.create-user
    ## Filesystems
    - usegalaxy-eu.autofs     # Setup the mount points which will be needed later

    - galaxyproject.tusd
