---
- name: Install and configure rustus
  hosts: upload
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/sentry.yml
    - mounts/mountpoints.yml
    - mounts/dest/all.yml
  vars:
    upload_dir_test: /data/jwd04/tus_upload/test
    upload_dir_main: /data/jwd04/tus_upload/main
    rustus_version: "0.7.3"
    rustus_instances:
      - name: test_uploads
        # user that rustus will run as
        user: "{{ user_name }}"
        # group that rustus will run as
        group: "{{ user_group_name }}"
        # args passed to rustus
        args:
          - --host "{{ inventory_hostname }}"
          - --port 1080
          - "--data-dir {{ upload_dir_test }}"
          - --hooks-http-urls "https://test.usegalaxy.eu/api/upload/hooks"
          - --hooks-http-proxy-headers "X-Api-Key,Cookie"
          - --hooks "pre-create"
          - --hooks-format tusd
          - --url "/api/upload/resumable_upload"
          - --max-body-size 20000000
          - "--sentry-dsn {{ sentry_dsn.test }} --sentry-sample-rate 1.0"
      - name: main_uploads
        # user that rustus will run as
        user: "{{ user_name }}"
        # group that rustus will run as
        group: "{{ user_group_name }}"
        # args passed to rustus
        args:
          - --host "{{ inventory_hostname }}"
          - --port 1081
          - "--data-dir {{ upload_dir_main }}"
          - --hooks-http-urls "https://usegalaxy.eu/api/upload/hooks"
          - --hooks-http-proxy-headers "X-Api-Key,Cookie"
          - --hooks "pre-create"
          - --hooks-format tusd
          - --url "/api/upload/resumable_upload"
          - --max-body-size 20000000
          - "--sentry-dsn {{ sentry_dsn.main }} --sentry-sample-rate 1.0"
  pre_tasks:
    - ansible.posix.firewalld:
        zone: public
        port: 1080-1081/tcp
        permanent: true
        state: enabled

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
        enable_create_user: true
        enable_kernel_5: true
        enable_install_software: true
    - influxdata.chrony
    ## Filesystems
    - usegalaxy-eu.autofs     # Setup the mount points which will be needed later

    - usegalaxy_eu.rustus
