- name: Install and configure tusd
  hosts: upload
  become: true
  become_user: root
  vars:
    tusd_instances:
      - name: uploads
        # user that tusd will run as
        user: tusd
        # group that tusd will run as
        group: tusd
        # args passed to tusd
        args:
          - -host=c8ac4630-d051-4b81-a2fa-58f2caa2fb08.fr.bw-cloud-instance.org
          - -port=1080
          - -upload-dir=/data/uploads
          - -hooks-http=https://usegalaxy.eu/api/upload/_resumable_upload
          - -hooks-http-forward-headers=Cookie
  pre_tasks:
    - name: tusd account group
      ansible.builtin.group:
        name: "{{ item.group }}"
        state: present
      loop: "{{ tusd_instances }}"
    - name: tusd account user
      ansible.builtin.user:
        name: "{{ item.user }}"
        group: "{{ item.group }}"
        shell: /sbin/nologin
        state: present
        comment: Tusd Service-Acct
      loop: "{{ tusd_instances }}"
  roles:
    - galaxyproject.tusd