---

# 100 GB
cvmfs_quota_limit: 100000

# symlinks for deps must exist due to path issues
links:
  - path: /galaxy
    src: /galaxy-repl
    force: yes
  - path: /galaxy-repl/test/deps
    src: /cvmfs/test.galaxyproject.org/deps
    force: yes
