---

# 100 GB
cvmfs_quota_limit: 100000

group_packages:
  - collectl

directories:
  - path: /galaxy-repl/test
  - path: /galaxy-repl/main
  - path: /var/lib/slurm
    mode: "0755"

# symlinks for deps must exist due to path issues
links:
  - path: /galaxy
    src: /galaxy-repl
    force: yes
  - path: /galaxy-repl/test/deps
    src: /cvmfs/test.galaxyproject.org/deps
    force: yes
  - path: /galaxy-repl/main/deps
    src: /cvmfs/main.galaxyproject.org/deps
    force: yes

jetstream_nfs_filesystems:
  - device: "10.0.0.6:/scratch0"
    mountpoint: /jetstream/iu-scratch0
