---
- file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy systemd environment override
  template:
    src: docker-env.conf
    dest: /etc/systemd/system/docker.service.d/custom.conf
    owner: root
    group: root
    mode: 0644
  register: docker_override

- name: restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: docker_override.changed
