---
galaxy_root_dir: /usr/local/galaxy/galaxy-dist
galaxy_tool_dir: "{{ galaxy_root_dir }}/tools"
galaxy_conf_dir: "{{ galaxy_root_dir }}/config"
galaxy_user: galaxy
galaxy_group: galaxy

galaxy_test_user:
    handlers:
        - handler1
        - handler2

