---

- name: restart mailman uwsgi
  command: service uwsgi restart mailman

- name: restart mailman
  service: name=mailman state=restarted

- name: restart spamassassin
  service: name=spamassassin state=restarted
