---

# node, npm for GIE proxy
group_packages:
  - nodejs
  - npm
  - docker-engine
  - collectl

group_yum_repositories:
  - name: docker
    contents:
      name: Docker
      baseurl: https://yum.dockerproject.org/repo/main/centos/6
      enabled: "1"
      gpgcheck: "1"
      gpgkey: https://yum.dockerproject.org/gpg

group_services:
  - name: docker
    state: stopped
    enabled: "no"

cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

cvmfs_http_proxies:
  - "DIRECT"
