---

group_groups:
  - name: slurm
    gid: 40302

group_users:
  - name: slurm
    group: slurm
    comment: 'Slurm Workload Manager'
    uid: 40302
    system: yes
    home: /var/lib/slurm
    shell: /bin/bash

controller_name: galaxy02
controller_ip: 129.114.60.174

slurm_yum_repo_baseurl: https://depot.galaxyproject.org/yum/el/$releasever/$basearch

slurmd_spool_dir: /var/tmp/slurmd.spool
slurmctld_state_dir: /tmp/slurm.state
