---
- name: autofs package install
  package:
    name: autofs
    state: latest

- name: autofs master
  template:
    src: auto.master.j2
    dest: /etc/auto.master
    owner: root
    group: root
    mode: 0644

- name: Copy all other conf files
  copy:
    src: "auto.{{ item }}"
    dest: "/etc/auto.{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ usegalaxy_eu_autofs_mounts }}"

- name: autofs service enable
  service:
    name: autofs
    enabled: yes
    state: started
