---
- name: autofs package install
  package:
    name: autofs
    state: latest

- name: autofs map master
  copy:
    dest: /etc/auto.master
    content: |
      /data           /etc/auto.data          nfsvers=3

- name: autofs map config
  copy:
    dest: /etc/auto.config
    content: |
      condor  -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/system/config/&

- name: autofs map data
  copy:
    dest: /etc/auto.data
    content: |
      0       -rw,hard,intr,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data3/galaxy/net/data/&

- name: autofs service enable
  service:
    name: autofs
    enabled: yes
    state: started
