---

- name: Tasks for all hosts
  hosts: all
  remote_user: root
  roles:
    - role: packages          # Install packages
      tags: system,packages
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: services          # Manage services
      tags: system,services
  tags: initial
