---

- name: Tasks for "base environment" hosts
  hosts: baseenv
  remote_user: root
  roles:
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: services          # Manage services
      tags: system,services
  tags: initial

- name: Tasks for stats servers
  hosts: statsservers
  remote_user: root
  vars_files:
    - secret_group_vars/ssl.yml
  roles:
    - role: geerlingguy.repo-epel
      tags: packages
    - role: galaxyprojectdotorg.nginx
      tags: nginx
    - role: galaxyprojectdotorg.postgresql
      tags: postgres
    - role: sentry
      tags: sentry
    - role: supervisor
      tags: supervisor

- name: Database tasks for stats servers
  hosts: statsservers
  remote_user: root
  become: yes
  become_method: sudo
  become_user: postgres
  roles:
    - role: natefoo.postgresql_objects
      tags: postgres
