---

group_groups:
  - name: slurm
    gid: 40302

group_users:
  - name: slurm
    group: slurm
    comment: 'Slurm Workload Manager'
    uid: 40302
    system: yes
    home: /var/lib/slurm
    shell: /bin/bash

slurm_yum_repo_baseurl: https://depot.galaxyproject.org/yum/el/$releasever/$basearch

slurmd_spool_dir: /var/lib/slurm/slurmd/slurmd.spool
slurmctld_state_dir: /var/lib/slurm/slurmctld/slurm.state

slurm_nodes:
  - real_memory: 29997
    sockets: 10
    partition: large
    name_prefix: jetstream-tacc-large
    nodes:
      - addr: 10.0.0.40
      - addr: 10.0.0.41
      - addr: 10.0.0.42
      - addr: 10.0.0.43
