---
- name: Install all of the necessary dependencies
  pip:
    virtualenv: "{{ grt_dir }}/venv/"
    requirements: "{{ grt_dir }}/code/requirements.txt"
  notify: 'reload grt'

- name: Install postgres client on centos/rhel
  package:
    name: postgresql
    state: present
  when: ansible_distribution_file_variety == "RedHat"
