---
- name: Get a list of all files in the directory
  find:
    paths: "{{ directory_path }}"
    patterns: "*"
    file_type: file
  register: files_to_modify

- name: Append file contents to each file
  lineinfile:
    path: "{{ item.path }}"
    insertafter: EOF
    line: "{{ lookup('file', file_to_append) }}"
  loop: "{{ files_to_modify.files }}"
   