# ggb Configuration
ggb_galaxy_db_url: postgres
ggb_redirect_url: "https://usegalaxy.eu"
ggb_galaxy_idsecret: "DEFAULT IS INSECURE!"
ggb_trainings:
  - test

# ggb Deployment
ggb_dir: /opt/ggb
ggb_user: root
ggb_group: root
ggb_version: master
