jobs:
 - name: crabby.galaxy.uni-freiburg.de.login
   type: selenium
   url:  https://galaxy.uni-freiburg.de/root/login
   interval: 30

 - name: crabby.galaxy.uni-freiburg.de.index
   type: selenium
   url:  https://galaxy.uni-freiburg.de
   interval: 30
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

 - name: crabby.galaxy.uni-freiburg.de.tool_jbrowse
   type: selenium
   url:  https://galaxy.uni-freiburg.de/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fjbrowse%2Fjbrowse%2F0.5.2&version=0.5.2
   interval: 120
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

 - name: crabby.galaxy.uni-freiburg.de.library_list
   type: selenium
   url:  https://galaxy.uni-freiburg.de/library/list
   interval: 120
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

 - name: crabby.galaxy.uni-freiburg.de.workflow_list
   type: selenium
   url:  https://galaxy.uni-freiburg.de/workflow/list_published
   interval: 120
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

 - name: crabby.galaxy.uni-freiburg.de.local_tool
   type: selenium
   url:  https://galaxy.uni-freiburg.de/?tool_id=sort1
   interval: 120
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

selenium:
 url: http://selenium:4444/wd/hub
 job-stagger-offset: 30

storage:
    graphite:
        host: grafana.denbi.uni-freiburg.de
        port: 2003
        metric-namespace: "crabby.crabby-{{ dc }}"
        tags:
            - "crabby-{{ dc }}"

report-internal-metrics: true
internal-metrics-gathering-interval: 15
