jobs:
 - name: crabby.galaxy.uni-freiburg.de.login
   type: selenium
   url:  https://galaxy.uni-freiburg.de/root/login
   interval: 30

 - name: crabby.galaxy.uni-freiburg.de.index
   type: selenium
   url:  https://galaxy.uni-freiburg.de
   interval: 30
   cookies:
    - name: galaxysession
      domain: galaxy.uni-freiburg.de
      path: /
      value: "{{ galaxysession_cookie }}"
      secure: true

selenium:
 url: http://selenium:4444/wd/hub
 job-stagger-offset: 30

storage:
    graphite:
        host: grafana.denbi.uni-freiburg.de
        port: 2003
        metric-namespace: "crabby.crabby-{{ dc }}"
        tags:
            - "crabby-{{ dc }}"

report-internal-metrics: true
internal-metrics-gathering-interval: 15
