---

nginx_conf_ssl_certificate: /etc/nginx/ssl/wildcard_cert.pem
nginx_conf_ssl_certificate_key: /etc/nginx/ssl/wildcard_privatekey.pem

nginx_configs:
  - graphite
  - sentry

nginx_default_redirect_uri: https://sentry.galaxyproject.org/
