---
- name: Install NetworkManager module
  yum:
    name: NetworkManager-config-routing-tables
    state: present

- name: Upload ifcfg files
  copy:
    src: '{{ item }}'
    dest: '/etc/sysconfig/network-scripts/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - ifcfg-eth0
    - ifcfg-eth1

- name: Update sysctl configuration
  copy:
    src: 99-multinic.conf
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: 0644

- name: Create second routing table
  copy:
    src: rt_tables
    dest: /etc/iproute2/rt_tables
    owner: root
    group: root
    mode: 0644

- name: Upload routing modifications:
  copy:
    src: route-eth1
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
- template:
    src: rule-eth1.j2
    dest: /etc/sysconfig/network-scripts/rule-eth1
    owner: root
    group: root
    mode: 0644

- name: Deploy networking hotfix script
  copy:
    src: fix-network.sh
    dest: /usr/sbin/fix-network
    owner: root
    group: root
    mode: 0755

- name: Restart network
  service:
    name: network
    state: restarted

- name: Execute it anyway
  command: /usr/sbin/fix-network

- name: Deploy systemd unit
  copy:
    src: fix-network.service
    dest: /etc/systemd/system/fix-network.service
    owner: root
    group: root
    mode: 0644

- name: Make sure the service is running
  systemd:
    daemon_reload: yes
    state: started
    name: fix-network
    enabled: yes
