---
# geerlingguy.repo-epel role doesn't enable (yet) PowerTools repository
# but EPEL packages may depend on packages from it
- name: Enable PowerTools repository Centos8.2
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "8.2"

- name: Enable PowerTools repository Centos8.4
  ini_file:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "8.4"