---
- name: Deploy the instance
  os_server:
    state: present
    name: "{{ server_names[0] }}"
    image: "{{ server.image | default('CentOS Server 7 RAW') }}"
    key_name: "{{ server.key_name | default('cloud2')}}"
    flavor: "{{ server.flavor | default('m1.small')}}"
    nics: "{{ server.nics | default('net-name=public-new')}}"
    security_groups: "{{ server.security_groups }}"
    userdata: "{{ server.userdata | default(None) }}"
  register: server

- debug: var=server

- name: Set DNS entries
  route53:
    command: create
    zone: "usegalaxy.eu"
    record: "{{ item }}"
    type: A
    ttl: 7200
    value: "{{ server.server.public_v4 }}"
    wait: yes
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    overwrite: true
  with_items: "{{ server_names }}"
  when: set_dns | default(true)
