---

# Note: This will only work with Debian-based hosts

- name: Install packages for NFS clients
  apt:
    pkg: "autofs-ldap"

- name: Install autofs defaults
  template:
    src: "default-autofs.j2"
    dest: "/etc/default/autofs"
    owner: "root"
    group: "root"
    mode: 0444
    backup: "yes"
  notify:
    - reload autofs

- name: Add /nfs directory for automount
  file:
    path: "/nfs"
    owner: "root"
    group: "root"
    mode: 0755
    state: "directory"

- name: Set up symlink parents
  file:
    dest: "{{ item.dest | dirname }}"
    state: "directory"
    mode: 0755
  with_items: nfs_symlinks
  when: nfs_symlinks is defined

- name: Set up symlinks
  file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: "link"
    force: yes
  with_items: nfs_symlinks
  when: nfs_symlinks is defined

- name: stat /home
  stat:
    path: "/home"
    follow: no
  register: home_stat
  when: nfs_home_link is defined

- name: Rename /home to /home.orig
  command:
    args: mv /home /home.orig
  when: nfs_home_link is defined and home_stat.stat.isdir is defined and home_stat.stat.isdir == true

- name: Set up /home symlink
  file:
    dest: "/home"
    src: "{{ nfs_home_link }}"
    state: "link"
    force: yes
  when: nfs_home_link is defined
