---
# Basic MariaDB install/config mainly for use by SlurmDBD

- name: Include install tasks for RedHat
  include: install_redhat.yml
  when: ansible_os_family == "RedHat"

- name: Disable network listening
  ini_file:
    path: /etc/my.cnf.d/server.cnf
    section: mysqld
    option: skip-networking
    value: ' # set by Ansible'
    no_extra_spaces: true
  notify:
    - restart mariadb
  when: mariadb_allow_network is undefined or mariadb_allow_network is defined and not mariadb_allow_network

- name: Start and enable MariaDB
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_pass }}"
  ignore_errors: yes  # will fail after the first time

- name: Add users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    login_password: "{{ mariadb_root_pass }}"
  with_items: "{{ mariadb_users }}"

- name: Add databases
  mysql_db:
    name: "{{ item.name }}"
    login_password: "{{ mariadb_root_pass }}"
  with_items: "{{ mariadb_databases }}"
