---
allow_duplicates: true
dependencies: []
galaxy_info:
  author: tkimball83
  description: RHEL/CentOS - Package upgrades, permissions setting, plugin configuration and scheduled updates
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - cron
    - packaging
    - yum
...
