---
- name: "Deploy fixer upper script"
  copy:
    content: |
        #!/bin/bash
        # Workflows are currently being assigned to _default_ which is wrong
        # https://github.com/galaxyproject/galaxy/issues/8209
        while true; do
                psql -c "COPY (update workflow_invocation set handler = 'handler_main_' || (random() * 12)::integer where (state = 'new' and handler = '_default_') or (state = 'new' and create_time < (now() - '1 minute'::interval)) returning workflow_invocation.id) to STDOUT with CSV DELIMITER ',';" | ts | grep -v 'UPDATE 0'
                sleep 1;
        done
    dest: /usr/bin/galaxy-fix-unscheduled-workflows
    owner: root
    group: root
    mode: 0755

- name: Add to cron
  cron:
    name: "Fix unscheduled workflows galaxyproject/galaxy#8209"
    minute: "*/20"
    job: pgrep -f /usr/bin/galaxy-fix-unscheduled-workflows > /dev/null || /usr/bin/galaxy-fix-unscheduled-workflows &
    user: galaxy
