

linuxbrew_user_name: jenkins
linuxbrew_user_home: /var/lib/jenkins
linuxbrew_user_shellrc: "{{ linuxbrew_user_home }}/.bashrc"

linuxbrew_taps:
  - homebrew/science
  - galaxyproject/tap
linuxbrew_recipes:
  - bcftools
  - planemo
  - node
