---

- name: reload slurmd
  service:
    name: "{{ slurmd_service_name }}"
    state: reloaded
  when: "'slurmexechosts' in group_names"

- name: reload slurmctld
  service:
    name: "{{ slurmctld_service_name }}"
    state: reloaded
  when: "'slurmservers' in group_names"

- name: reload slurmdbd
  service:
    name: "{{ slurmdbd_service_name }}"
    state: reloaded
  when: "'slurmdbdservers' in group_names"
