---
- name: Install useful tools
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - vim
    - htop
    - atop
    - strace
    - jq
    - iftop
    - wget
    - curl
    - tmux
    - git
    - nmap
    - tcpdump
    - net-tools
    - unzip
    - mutt
    - byobu
    # centos specific
    - setools-console
    - yum-utils

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
