---
- name: Install useful tools
  yum:
    name: "{{ admin_packages }}"
    state: installed

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Start atop
  service:
    name: atop
    state: started
    enabled: yes
