---
- name: Install useful tools
  yum:
    name: "{{ admin_packages | select | list }}"
    state: installed

- name: Start atop
  service:
    name: atop
    state: started
    enabled: yes
  when: "'atop' in admin_packages"
