---
- name: Ensure boto is available
  pip:
    name: boto

- name: Set DNS entries
  route53:
    command: create
    zone: "usegalaxy.eu"
    record: "{{ item.record }}"
    type: "{{ item.type }}"
    ttl: "{{ item.ttl | default(7200) }}"
    value: "{{ item.value }}"
    wait: yes
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    overwrite: true
  with_items:
    - record: usegalaxy.eu
      type: MX
      value: "10 mxa.mailgun.org,10 mxb.mailgun.org"
      ttl: 300
    - record: usegalaxy.eu
      type: TXT
      value: '"v=spf1 include:mailgun.org ~all"'
      ttl: 300
    - record: mailo._domainkey.usegalaxy.eu
      type: TXT
      value: '"k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDWqARw6lby+yJNifDd1Nf9FfegF2TB4VJAdupceZ6pAHwYvS/2WFUwc3ZxdA8+awjDfLr6cAWERnP6YsBqZ7/1jCvtvOM2RLvsKMrzKG+KycfSfaGfFLZw/qPHM+82Mz7o5PdmcVehDSjKrnRXWGjliF/bazOoPg4OJObmAlhovwIDAQAB"'
      ttl: 300
    - record: csp.usegalaxy.eu
      type: A
      value: 192.52.3.60
    - record: sql.usegalaxy.eu
      type: A
      value: 192.52.3.38
    - record: elk.usegalaxy.eu
      type: A
      value: 192.52.3.115
    - record: usegalaxy.eu
      type: A
      value: 192.52.3.222
    - record: ftp.usegalaxy.eu
      type: A
      value: 192.52.3.81
    - record: stats.usegalaxy.eu
      type: A
      value: 192.52.3.121
