---
- name: Ensure boto is available
  pip:
    name: boto

- name: Set DNS entries
  route53:
    command: create
    zone: "usegalaxy.eu"
    record: "{{ item.record }}"
    type: "{{ item.type }}"
    ttl: 7200
    value: "{{ item.value }}"
    wait: yes
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    overwrite: true
  with_items:
    - record: usegalaxy.eu
      type: A
      value: 192.52.3.205
    - record: csp.usegalaxy.eu
      type: A
      value: 192.52.3.60
    - record: sql.usegalaxy.eu
      type: A
      value: 192.52.3.38
    - record: elk.usegalaxy.eu
      type: A
      value: 192.52.3.115
    - record: proxy.usegalaxy.eu
      type: A
      value: 192.52.3.222
    - record: ftp.usegalaxy.eu
      type: A
      value: 192.52.3.25
