- include: ./lib/galaxy/files/templates/examples/production_azure.yml
- include: ./lib/galaxy/files/templates/examples/production_ftp.yml
- include: ./lib/galaxy/files/templates/examples/production_s3fs.yml
- include: ./lib/galaxy/files/templates/examples/production_aws_private_bucket.yml
- include: ./lib/galaxy/files/templates/examples/production_aws_public_bucket.yml
