---
- name: "Deploy maintenance scripts"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: galaxy
    group: galaxy
    mode: 0755
  loop:
    - { src: 'pbs.sh.j2', dest: "{{ maintenance_dir }}/pbs.sh" }
    - { src: 'uploads.sh.j2', dest: "{{ maintenance_dir }}/uploads.sh" }
    - { src: 'job_working_dir.sh.j2', dest: "{{ maintenance_dir }}/job_working_dir.sh" }

- name: "Deploy maintenance job files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: galaxy
    group: galaxy
    mode: 0655
  loop:
    - { src: 'pbs.job.j2', dest: "{{ maintenance_dir }}/pbs.job" }
    - { src: 'uploads.job.j2', dest: "{{ maintenance_dir }}/uploads.job" }
    - { src: 'job_working_dir.job.j2', dest: "{{ maintenance_dir }}/job_working_dir.job" }