---
- name: "Make parent dir"
  file:
    state: directory
    dest: "{{ pgs_dir }}"
    owner: telegraf
    group: telegraf
    mode: 0755

- name: "Clone repository"
  become: true
  become_user: telegraf
  umask: 0022
  git:
    repo: 'https://github.com/martenson/public-galaxy-servers/'
    dest: "{{ pgs_repo_dir }}"
    version: master
    force: yes

- name: "Fix perms here"
  file:
    state: directory
    dest: "{{ pgs_repo_dir }}"
    owner: telegraf
    group: telegraf
    mode: 0755

- name: "Template tool counter script"
  become: true
  become_user: telegraf
  template:
    src: count-tools.sh.j2
    dest: "{{ pgs_dir }}/count-tools.sh"
    mode: 0755

- name: "Install requirements"
  become: true
  become_user: telegraf
  pip:
    requirements: "{{ pgs_repo_dir }}/requirements.txt"
    virtualenv: "{{ pgs_dir }}/venv"
  umask: 0022

- name: "Fix perms here"
  file:
    state: directory
    dest: "{{ pgs_dir }}/venv"
    owner: telegraf
    group: telegraf
    mode: 0755

- name: "Install influxdb"
  become: true
  become_user: telegraf
  pip:
    name: influxdb
    virtualenv: "{{ pgs_dir }}/venv"
