---
- name: Add env vars in bashrc
  become: true
  become_user: "{{ galaxy_user }}"
  lineinfile:
    path: "~/.bashrc"
    regexp: "^export {{ item.var }}"
    line: "export {{ item.var }}='{{ item.val }}'"
  with_items:
    - var: PGUSER
      val: "{{ postgres_user }}"
    - var: PGHOST
      val: "{{ postgres_host }}"

- name: Copy using the 'content' for inline data
  become: true
  become_user: "{{ galaxy_user }}"
  copy:
    content: |
      {{ postgres_host }}:{{ postgres_port }}:*:{{ postgres_user }}:{{ postgres_pass }}
    dest: "~/.pgpass"
