---
- name: Ensure that defined packages are present
  tags: yum
  become: true
  yum:
    allow_downgrade: "{{ yum_module_opts.allow_downgrade|default('no') }}"
    conf_file: "{{ yum_module_opts.conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_module_opts.disable_gpg_check|default('no') }}"
    disablerepo: "{{ yum_module_opts.disablerepo|join(',')|default(omit) }}"
    enablerepo: "{{ yum_module_opts.enablerepo|join(',')|default(omit) }}"
    exclude: "{{ yum_module_opts.exclude|default(omit) }}"
    installroot: "{{ yum_module_opts.installroot|default('/') }}"
    name: "{{ item }}"
    security: "{{ yum_module_opts.security|default('no') }}"
    skip_broken: "{{ yum_module_opts.skip_broken|default('no') }}"
    state: present
    update_cache: "{{ yum_module_opts.update_cache|default('no') }}"
    validate_certs: "{{ yum_module_opts.validate_certs|default('yes') }}"
  with_items: "{{ yum_packages_install }}"
  when: yum_packages_install|length > 0

- name: Ensure that defined packages are absent
  tags: yum
  become: true
  yum:
    allow_downgrade: "{{ yum_module_opts.allow_downgrade|default('no') }}"
    conf_file: "{{ yum_module_opts.conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_module_opts.disable_gpg_check|default('no') }}"
    disablerepo: "{{ yum_module_opts.disablerepo|join(',')|default(omit) }}"
    enablerepo: "{{ yum_module_opts.enablerepo|join(',')|default(omit) }}"
    exclude: "{{ yum_module_opts.exclude|default(omit) }}"
    installroot: "{{ yum_module_opts.installroot|default('/') }}"
    name: "{{ item }}"
    security: "{{ yum_module_opts.security|default('no') }}"
    skip_broken: "{{ yum_module_opts.skip_broken|default('no') }}"
    state: absent
    update_cache: "{{ yum_module_opts.update_cache|default('no') }}"
    validate_certs: "{{ yum_module_opts.validate_certs|default('yes') }}"
  with_items: "{{ yum_packages_remove }}"
  when: yum_packages_remove|length > 0
...
