---
- name: Ensure that the required yum plugins are installed
  tags: yum
  become: true
  yum:
    allow_downgrade: "{{ yum_module_opts.allow_downgrade|default('no') }}"
    conf_file: "{{ yum_module_opts.conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_module_opts.disable_gpg_check|default('no') }}"
    disablerepo: "{{ yum_module_opts.disablerepo|join(',')|default(omit) }}"
    enablerepo: "{{ yum_module_opts.enablerepo|join(',')|default(omit) }}"
    exclude: "{{ yum_module_opts.exclude|default(omit) }}"
    installroot: "{{ yum_module_opts.installroot|default('/') }}"
    name: "{{ item }}"
    security: "{{ yum_module_opts.security|default('no') }}"
    skip_broken: "{{ yum_module_opts.skip_broken|default('no') }}"
    state: present
    update_cache: "{{ yum_module_opts.update_cache|default('no') }}"
    validate_certs: "{{ yum_module_opts.validate_certs|default('yes') }}"
  register: yum_plugins_yum
  with_items: "{{ yum_plugin_packages }}"

- block:
    - name: Applying yum plugins configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: yum-fastestmirror.conf.j2, dest: /etc/yum/pluginconf.d/fastestmirror.conf }
        - { src: yum-post-transaction-actions.conf.j2, dest: /etc/yum/pluginconf.d/post-transaction-actions.conf }

    - name: Applying post-transaction actions (if applicable)
      lineinfile:
        attributes: "{{ item.attributes|default(omit) }}"
        backrefs: "{{ item.backrefs|default('no') }}"
        backup: "{{ item.backup|default('no') }}"
        create: "{{ item.create|default('yes') }}"
        group: "{{ item.group|default('root') }}"
        insertafter: "{{ item.insertafter|default(omit) }}"
        insertbefore: "{{ item.insertbefore|default(omit) }}"
        line: "{{ item.action_key }}:{{ item.transaction_state }}:{{ item.command }}"
        mode: "{{ item.mode|default(0600) }}"
        others: "{{ item.others|default(omit) }}"
        owner: "{{ item.owner|default('root') }}"
        path: "{{ yum_plugin_post_transaction_actions.actiondir }}/{{ item.action_key }}.action"
        regexp: "^{{ item.action_key }}"
        state: "{{ item.state|default('present') }}"
        unsafe_writes: "{{ item.unsafe_writes|default(omit) }}"
        validate: "{{ item.validate|default(omit) }}"
      with_items: "{{ yum_plugin_post_transaction_actions.actions }}"
      when:
        - item.action_key is defined
        - item.transaction_state is defined
        - item.command is defined
  tags: yum
  become: true
  when: yum_plugins_yum|success
...
