---
- name: Check for bashrc
  stat:
    path: "{{ user.home }}/.bashrc"
  register: bashrc_stat_out
  become: true
  become_user: "{{ user.name }}"

- name: Copy default bashrc when not existing
  copy:
    src: /etc/skel/.bashrc
    dest: "{{ user.home }}/.bashrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    remote_src: yes
    mode: 0750
  when: not bashrc_stat_out.stat.exists
