---
- name: "Make parent dir"
  file:
    dest: "{{ pgs_dir }}"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: "Clone repository"
  become: true
  become_user: ubuntu
  git:
    repo: 'https://github.com/martenson/public-galaxy-servers/'
    dest: "{{ pgs_repo_dir }}"
    version: master

- name: "Template runner script"
  become: true
  become_user: ubuntu
  template:
    src: script.sh.j2
    dest: "{{ pgs_repo_dir }}.sh"
    mode: 0750

- name: "Template runner script"
  become: true
  become_user: ubuntu
  template:
    src: count-tools.sh.j2
    dest: "{{ pgs_dir }}.sh"
    mode: 0750

- name: "Install requirements"
  become: true
  become_user: ubuntu
  pip:
    requirements: "{{ pgs_repo_dir }}/requirements.txt"
    virtualenv: "{{ pgs_dir }}/venv"

- name: "Install influxdb"
  become: true
  become_user: ubuntu
  pip:
    name: influxdb
    virtualenv: "{{ pgs_dir }}/venv"

- name: "Configure hourly cron job"
  cron:
    name: "run public-galaxy-server collector/processing"
    minute: "0"
    hour: "*"
    user: ubuntu
    job: "bash {{ pgs_repo_dir }}.sh"
