---
telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["http://grafana.denbi.uni-freiburg.de:8086"]
    - database = "rancher"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: netstat
