---

local_users:
  - name: launch
    comment: 'Galaxy Cloud Launch'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'

directories:
  - path: /srv/cloudlaunch
    owner: launch
    group: launch
  - path: /srv/nginx
    owner: sites
    group: sites
