---

linux_console: ttyS1,115200n8

packages:
  - git
  - postgresql-9.4
  # TS dependencies
  - autoconf 
  - automake 
  - build-essential
  - gfortran
  - cmake
  - git-core
  - libatlas-base-dev
  - libblas-dev
  - liblapack-dev
  - openssl
  - python-dev
  - python2.6
  - python2.6-dev
  - python-setuptools
  - python-virtualenv
  - zlib1g-dev
  - libyaml-dev
  - subversion
  - python-dev
  - pkg-config
