---

linux_console: ttyS1,115200n8

host_apt_repositories:
  - 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
host_packages:
  - git
  - postgresql-9.4
  - python-virtualenv
  - jenkins
  # TS packages
  - autoconf
  - automake
  - build-essential
  - gfortran
  - cmake
  - git-core
  - libatlas-base-dev
  - libblas-dev
  - liblapack-dev
  - openssl
  - python-dev
  - python-setuptools
  - python-virtualenv
  - zlib1g-dev
  - libyaml-dev
  - subversion
  - python-dev
  - pkg-config
  - unzip
  - docker.io
  - samtools
  - sudo
  - curl
  - nodejs
  - npm

local_users:
  - name: jenkins
    groups: docker

crontabs:
  - id: jenkins_backup
    name: Jenkins Backup
    user: jenkins
    hour: 22
    minute: 0
    job: rsync -e 'ssh -i ~/.ssh/id_rsa_zfsdump' -av --delete /var/lib/jenkins/ zfsdump-n2@westvleteren.galaxyproject.org:/zones/westvleteren/backup/n2/jenkins && ssh -T zfsdump-n2@westvleteren.galaxyproject.org -- /usr/sbin/zfs snapshot zones/westvleteren/backup/n2/jenkins@`date -u +\%Y\%m\%dT\%H\%M\%SZ`
