---
# defaults file for galaxyproject.galaxy

# TODO: Magical restarters depending on how you're running Galaxy.
#- name: restart galaxy
  #debug:
    #msg: "RESTARTER NOT IMPLEMENTED - Please restart Galaxy manually"

- name: swap zerglings
  shell: source /opt/galaxy/.bashrc && /usr/bin/gxadmin zerg swap
  listen: restart galaxy
  args:
    executable: /bin/bash

- name: swap handlers
  shell: source /opt/galaxy/.bashrc && /usr/bin/gxadmin handler restart
  listen: restart galaxy
  args:
    executable: /bin/bash
