---

- name: Check master CA cert existence
  stat:
    path: "{{ docker_ssl_ca_dir }}/ca.pem"
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  run_once: true
  register: docker_ssl_ca_cert_stat_out
  when: docker_ssl_ca_cert is not defined

- name: Include tasks to create CA cert
  include: ssl-gen-ca.yml
  when: docker_ssl_ca_cert is not defined and "'dockersslcamaster' in group_names and not docker_ssl_ca_cert_stat_out.stat.exists"
