---

- name: Include CA cert tasks
  include: ssl-ca.yml

- name: Distribute CA cert from docker SSL master
  synchronize:
    src: "{{ docker_ssl_ca_dir }}/ca.pem"
    dest: "/etc/docker/ca.pem"
    # https://github.com/ansible/ansible/issues/16215
    ssh_args: "-l {{ ansible_user }}"
    rsync_path: "/usr/bin/sudo /usr/bin/rsync"
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  when: docker_ssl_ca_cert is not defined

- name: Distribute CA cert from playbook
  copy:
    content: "{{ docker_ssl_ca_cert }}"
    dest: "/etc/docker/ca.pem"
  when: docker_ssl_ca_cert is defined

- name: Set CA server directory fact
  set_fact:
    docker_ssl_ca_server_dir: "{{ docker_ssl_ca_dir }}/{{ inventory_hostname }}"

- name: Check master server cert(s) existence
  stat:
    path: "{{ docker_ssl_ca_server_dir }}/server-cert.pem"
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  register: docker_ssl_ca_server_cert_stat_out
  when: docker_ssl_server_certs[inventory_hostname] is not defined

- name: Include tasks to create server cert(s)
  include: ssl-gen-server-cert.yml
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  when: docker_ssl_server_certs[inventory_hostname] is not defined and not docker_ssl_ca_server_cert_stat_out.stat.exists

- name: Distribute server certs from docker SSL master
  synchronize:
    src: "{{ docker_ssl_ca_server_dir }}/server-cert.pem"
    dest: "/etc/docker/server-cert.pem"
    ssh_args: "-l {{ ansible_user }}"
    rsync_path: "/usr/bin/sudo /usr/bin/rsync"
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  when: docker_ssl_server_certs[inventory_hostname] is not defined

- name: Distribute server certs from playbook
  copy:
    content: "{{ docker_ssl_server_certs[inventory_hostname] }}"
    dest: "/etc/docker/server-cert.pem"
  when: docker_ssl_server_certs[inventory_hostname] is defined

- name: Distribute server keys from docker SSL master
  synchronize:
    src: "{{ docker_ssl_ca_server_dir }}/server-key.pem"
    dest: "/etc/docker/server-key.pem"
    perms: yes
    ssh_args: "-l {{ ansible_user }}"
    rsync_path: "/usr/bin/sudo /usr/bin/rsync"
  delegate_to: "{{ groups.dockersslcamaster[0] }}"
  when: docker_ssl_server_keys[inventory_hostname] is not defined

- name: Distribute server keys from playbook
  copy:
    content: "{{ docker_ssl_server_keys[inventory_hostname] }}"
    dest: "/etc/docker/server-key.pem"
    mode: "0400"
  when: docker_ssl_server_keys[inventory_hostname] is defined

- name: Set docker daemon options for SSL
  set_fact:
    docker_daemon_option_list: "{{ docker_daemon_option_list }} + [ '--tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem' ]"
    docker_daemon_listen_network: "{{ docker_daemon_listen_network | default('tcp://0.0.0.0:2376') }}"
