http:
  middlewares:
#    basic-auth:
#      basicAuth:
#        usersFile: "/rules/htpasswd"
    redirect-scheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirect-to-non-www:
      redirectRegex:
        regex: "^https://www\\.(.*)"
        replacement: "https://${1}"
        permanent: true
    error-pages:
      errors:
        status:
          - "418"
          - "400"
          - "404"
          - "4402-599"
        query: /{status}.html
        service: errors
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth?authelia-url=https://authelia.traefik.flyingrabb.it"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
          # https://community.traefik.io/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732
          # X-Forwarded-Proto: "https"
    rate-limit:  
      rateLimit:
        average: 100
        burst: 50
