---
# Certs
- name: mkdir
  file:
    path: "~/.docker"
    state: directory
    mode: '0750'

- name: Setup docker for user
  copy:
    src: "{{ item }}"
    dest: "~/.docker/{{ item }}"
    mode: "0640"
  with_items:
    - ca.pem
    - cert.pem
    - key.pem

- name: Add env vars
  lineinfile:
    path: "~/.bashrc"
    regexp: "^export {{ item.var }}"
    line: "export {{ item.var }}='{{ item.val }}'"
  with_items:
    - var: DOCKER_HOST
      val: 'tcp://docker.galaxyproject.eu:443'
    - var: DOCKER_TLS_VERIFY
      val: 1
    - var: DOCKER_CERT_PATH
      val: "{{ galaxy_root }}/.docker"
