---
- name: "Deploy script"
  copy:
    content: |
        #!/bin/bash
        for dir in {custom-tools,dynamic_rules,interactive_environments,mutable-config,mutable-data,server,venv,tool-data}; do
            rsync -avr --delete --exclude client/node_modules $dir/ {{ galaxy_nfs_location }}/$dir/;
        done;
    dest: /usr/bin/galaxy-sync-to-nfs
    owner: root
    group: root
    mode: 0755

#- name: Add to cron
  #cron:
    #name: "Fix unscheduled jobs"
    #minute: "*/20"
    #job: /usr/bin/galaxy-fix-unscheduled-jobs
    #user: galaxy
