- name: Creates crabby config directory
  file: path=/etc/crabby/ state=directory

- name: Copy configuration file
  template:
    src: crabby.yml
    dest: /etc/crabby/config.yml
    owner: root
    group: root
    mode: 0644

- name: Crabby docker-compose services
  docker_service:
    project_name: crabby
    definition:
      version: '2'
      services:
        selenium:
          image: selenium/standalone-chrome
        crabby:
          image: chrissnell/crabby
          environment:
            CRABBY_CONFIG: /config/config.yml
          volumes:
           - /etc/crabby:/config
          depends_on:
          - selenium
          links:
          - selenium

# We want telegraf to be able to monitor docker.
- name: add user to docker group
  user: name=telegraf groups=docker append=yes
  sudo: true
  register: user_task
  
- name: Kill open ssh sessions
  shell: "ps -ef | grep sshd | grep `whoami` | awk '{print \"kill -9\", $2}' | sh"
  when: user_task | changed
  failed_when: false
