- name: Creates crabby config directory
  file: path=/etc/crabby/ state=directory

- name: Copy configuration file
  template:
    src: crabby.yml
    dest: /etc/crabby/config.yml
    owner: root
    group: root
    mode: 0644

- name: Crabby docker-compose services
  docker_service:
    project_name: crabby
    definition:
      version: '2'
      services:
        selenium:
          image: selenium/standalone-chrome
        crabby:
          image: chrissnell/crabby
          environment:
            CRABBY_CONFIG: /config/config.yml
          volumes:
           - /etc/crabby:/config
          depends_on:
          - selenium
          links:
          - selenium
