- cron:
    job: /usr/bin/fix-conda-env
    minute: 0
  become: true
  become_user: galaxy

- copy:
    name: "Fix conda env"
    src: "fix-conda.sh"
    dest: /usr/bin/fix-conda-env
    mode: '0755'
    owner: root
    group: root

- copy:
    src: "fix-ftp.sh"
    dest: /usr/bin/fix-ftp
    mode: '0755'
    owner: root
    group: root

- cron:
    name: "Fix ftp"
    job: /usr/bin/fix-ftp
    minute: "*/15"
  become: true
  become_user: galaxy
