---
- name: Ensure that all yum packages are latest
  tags: yum
  become: true
  yum:
    allow_downgrade: "{{ yum_module_opts.allow_downgrade|default('no') }}"
    conf_file: "{{ yum_module_opts.conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_module_opts.disable_gpg_check|default('no') }}"
    disablerepo: "{{ yum_module_opts.disablerepo|join(',')|default(omit) }}"
    enablerepo: "{{ yum_module_opts.enablerepo|join(',')|default(omit) }}"
    exclude: "{{ yum_module_opts.exclude|default(omit) }}"
    installroot: "{{ yum_module_opts.installroot|default('/') }}"
    name: '*'
    security: "{{ yum_module_opts.security|default('no') }}"
    skip_broken: "{{ yum_module_opts.skip_broken|default('no') }}"
    state: latest
    update_cache: "{{ yum_module_opts.update_cache|default('no') }}"
    validate_certs: "{{ yum_module_opts.validate_certs|default('yes') }}"
  register: yum_update_yum

- name: Gathering facts post package upgrades
  tags: yum
  action:
    setup
  when: yum_update_yum|changed
...
