---
- name: Ensure that the yum-cron package is installed
  tags: yum
  become: true
  yum:
    allow_downgrade: "{{ yum_module_opts.allow_downgrade|default('no') }}"
    conf_file: "{{ yum_module_opts.conf_file|default(omit) }}"
    disable_gpg_check: "{{ yum_module_opts.disable_gpg_check|default('no') }}"
    disablerepo: "{{ yum_module_opts.disablerepo|join(',')|default(omit) }}"
    enablerepo: "{{ yum_module_opts.enablerepo|join(',')|default(omit) }}"
    exclude: "{{ yum_module_opts.exclude|default(omit) }}"
    installroot: "{{ yum_module_opts.installroot|default('/') }}"
    name: yum-cron
    security: "{{ yum_module_opts.security|default('no') }}"
    skip_broken: "{{ yum_module_opts.skip_broken|default('no') }}"
    state: present
    update_cache: "{{ yum_module_opts.update_cache|default('no') }}"
    validate_certs: "{{ yum_module_opts.validate_certs|default('yes') }}"
  register: yum_cron_yum

- block:
    - name: Applying yum-cron configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: root
        group: root
        mode: 0644
      notify: restart yum-cron
      with_items:
        - { src: yum-cron.conf.j2, dst: /etc/yum/yum-cron.conf }
        - { src: yum-cron-hourly.conf.j2, dst: /etc/yum/yum-cron-hourly.conf }

    - name: Enable and start the yum-cron service on boot
      service:
        enabled: yes
        name: yum-cron
        state: started
  tags: yum
  become: true
  when: yum_cron_yum|success
...
