---
- name: Applying yum protected.d configurations
  tags: yum
  become: true
  template:
    src: yum-protected.d.conf.j2
    dest: /etc/yum/protected.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ yum_protected }}"
  when: yum_protected[item]|length > 0
...
